#+LATEX_CLASS: extreport
#+LATEX_CLASS_OPTIONS: [12pt]
#+setupfile: ~/.emacs.d/org-latex-setupfiles/lang/ru.org
#+setupfile: ~/.emacs.d/org-latex-setupfiles/theorem/plain.org
#+LATEX_HEADER_EXTRA: \usepackage[tocpageword=true]{cmcmsu-gost}
#+title: Произведение Шура--Адамара линейных кодов в анализе теоретико-кодовых криптосистем
#+author: Чижов Иван Владимирович

* Введение
:PROPERTIES:
:UNNUMBERED: t
:END:
#+latex: \addcontentsline{toc}{chapter}{Введение}

*Актуальность темы*.
Обзор, введение в тему, обозначение места данной работы в мировых исследованиях и т.п., можно использовать ссылки на другие
работы.

Далее приводится пример.

Необходимость проведения научных исследований в целях создания перспективных средств обеспечения информацион ной безопасности определяется Доктриной информационной безопасности Российской Федерации.
Области применения результатов таких исследований определяются Федеральным законом "О безопасности критической информационной инфраструктуры Российской Федерации", постановлением Правительства РФ о реализации государственной программы "Информационное общество", а также рядом приказов отраслевых министерств и ведомств.

В подавляющем большинстве случаев использование средств обеспечения информационной безопасности возможно только после проведения процедуры их сертификации и проверки выполнения требований, предъявляемых ФСТЭК и ФСБ России.
При проведении указанной процедуры важным фактором является получение обоснованных оценок показателей мер защиты, реализуемых средствами защиты информации и, в частности, входящими в их состав криптографическими протоколами.
Высокий уровень защиты информации, обеспечиваемый криптографическими протоколами, является необходимым фактором для обоснования безопасности передаваемой информации.

При передаче информации ее безопасность обеспечивается, как правило, совокупностью нескольких криптографических протоколов:
+ протоколом односторонней, взаимной или многосторонней аутенти фикации участников информационного взаимодействия,
+ протоколом выработки общей для участников взаимодействия ключевой информации, действующей в рамках одной сессии информационного взаимодействия,
+ транспортным протоколом, предназначенным для передачи защищенной информации по каналам связи,
+ процедурами выработки производной ключевой информации, контроля за временем и объемом используемой ключевой информации,
+ вспомогательными протоколами, предназначенными для передачи ошибок информационного взаимодействия, квитирования абонентов, инициализации процедуры выработки нового сессионного ключа и т.п.

Указанной совокупностью протоколов ограничивается область диссертационных исследований.
Выбор конкретного криптографического протокола, применяемого в средстве защиты информации, проводится с учетом большого числа факторов, к которым могут быть отнесены\nbsp{}--- число участников информационного взаимодействия, объем передаваемой информации, срок действия информационной системы или телекоммуникационной сети связи, свойства открытого канала связи, по которому пере дается информация, тип используемой ключевой информации и т.д.

Различные эксплуатационные требования к применяемым криптографическим протоколам приводят к необходимости разработки как универсальных решений и включения таких решений в действующую в Российской Федерации систему стандартизации, так и разработки частных решений, специализированных для конкретных условий эксплуатации.
Однако во всех случаях необходимо обеспечение одинокого высокого уровня защиты информации.

*Степень разработанности темы*.
Этот раздел должен быть отдельным структурным элементом по ГОСТ, но он, как правило, включается в описание актуальности темы.
Нужен он отдельным структурынм элементом или нет --- смотрите другие диссертации вашего совета, скорее всего не нужен.

В диссертации решены актуаль ные и трудные математические задачи, представляющие исключительную важность для обеспечения защищенного взаимодействия средств защиты информации.
В рамках вводных разделов диссертации к каждой главе диссертации представлен исчерпывающий обзор предшествующих результатов по теме исследования, наиболее важные из которых указаны далее в разделе "Краткое содержание работы".

*Целью* данной работы является совершенствование методов построения криптографических протоколов, применяемых для обеспечения защищенного обмена информацией по открытым каналам связи, а также методов получения обоснованных оценок безопасности криптографических протоколов.

Для достижения поставленной цели необходимо было решить следующие *задачи*:
1. уточнить трудоемкость нахождения дискретных логарифмов в группах точек эллиптических кривых и построения параметров эллиптических кривых, обладающих заданной трудоемкостью решения задачи дискретного логарифмирования;
2. разработать способ выработки псевдослучайных последовательностей, удовлетворяющих предъявляемым требованиям по безопасности;
3. построить режим работы блочных шифров, реализующего аутентифицированное шифрование;
4. оценить численные значения показателей эффективности мер защиты для криптографических протоколов, используемых в средствах защиты информации;
5. Исследовать, разработать, вычислить и т.д. и т.п.
6. Исследовать, разработать, вычислить и т.д. и т.п.
7. Исследовать, разработать, вычислить и т.д. и т.п.
8. Исследовать, разработать, вычислить и т.д. и т.п.

*Научная новизна*:
# Опция нужна, чтобы список не отрывался от предыдущей строки
#+attr_latex: options: [beginpenalty=10000]
1. Впервые ...
2. Впервые ...
3. Было выполнено оригинальное исследование ...
4. Впервые получена верхняя оценка числа шагов алгоритма Госпера, используемого для поиска двух совпадающих элементов числовых последовательностей.
   Автором предложен метод дискретного логарифмирования в группе точек эллиптической кривой, в основе которого лежит алгоритм Госпера, и получена асимптотическая оценка трудоемкости предложенного метода.
   Соответствие асимптотической оценки получаемым на практике значениям подтверждено результатами практических экспериментов на ЭВМ.
5. Впервые доказана теорема об иррациональности значений действительных чисел, определяемых рядами специального вида. Предложены новые алгоритмы представления действительных чисел специального вида в виде систематической дроби по произвольному основанию и способ применения предложенных алгоритмов для выработки псевдослучайных последовательностей.
   Получены верхние оценки объема памяти, необходимого для реализации предложенных алгоритмов.

*Теоретическая значимость работы*.
Результаты исследования развивают методы оценки безопасности средств защиты информации, использующих математический аппарат эллиптических кривых.

Автором найден нетривиальный алгоритм решения задачи дискретного логарифмирования в группе точек эллиптической кривой, трудоемкость которого зависит от разыскиваемого неизвестного значения.
Это привело не только к корректировке методов выбора параметров эллиптических кривых, но и к необходимости выработки секретных ключей криптографических схем и протоколов из множества значений, на которых найденный алгоритм имеет максимальную трудоемкость.

Предложенный автором способ выработки псевдослучайных последовательностей удовлетворил требованиям, традиционно накладываемым на криптографические датчики случайных чисел, а также обеспечил ряд дополнительных эксплуатационных характеристик, например, существенно затруднил реализацию датчиков на программируемых логических интегральных схемах.

Разработанный в диссертации новый класс ключевых сжимающих отображений, а также свойства, которыми данный класс обладает, позволили не только разработать несколько новых режимов аутентификационного шифрования для блочных шифров, но и обеспечить возможность высокоэффективной реализации данных режимов на вычислительных средствах с различной архитектурой.

Разработанная в работе методика проведения исследований безопасности криптографических протоколов является на настоящий момент единственным математически обоснованным документом, позволяющим не только проводить комплексные исследования всех факторов, влияющих на безопасность криптографического протокола, но и получать численные значения показателей мер защиты информации.

*Практическая значимость*.
Результаты диссертационных исследований автора были использованы при подготовке положительных заключений о возможности применения ряда государственных стандартов и рекомендаций по стандартизации в области криптографической защиты информации, в частности, ГОСТ Р\nbsp{}34.10-2012 "Процессы формирования и проверки электронной цифровой подписи", Р\nbsp{}1323565.1.004-
2017 "Схемы выработки общего ключа с аутентификацией на основе открытого ключа", Р\nbsp{}1323565.1.018-2018 "Криптографические механизмы аутентификации в контрольных устройствах для автотранспорта", Р 1323565.1.024–2019 "Параметры эллиптических кривых для криптографических алгоритмов и протоколов", Р\nbsp{}1323565.1.028–2019 "Криптографические механизмы защищенного взаимодействия контрольных и измерительных устройств".

*Методология и методы исследования*.
В рамках диссертационного исследования применяются математические методы алгебры, теории чисел, алгебраической геометрии и теории функций комплексного переменного, теории вероятностей и математической статистики, а также теории автоматов.

*Основные положения, выносимые на\nbsp{}защиту*:
#+attr_latex: options: beginpenalty=10000
1. Первое положение
2. Второе положение
3. Третье положение
4. Четвертое положение
5. Доказательство теоремы 1.2 об оценке числа шагов алгоритма Госпера, используемого для поиска двух совпадающих элементов числовых последовательностей.
6. Алгоритм решения задачи дискретного логарифмирования в группе точек эллиптической кривой, основанный на методе Госпера и асимптотическая оценка сложности данного алгоритма.
7. Доказательство теоремы 1.3 об алгоритме дискретного логарифмирования в группе точек эллиптической кривой, использующего информацию о мультипликативном порядке неизвестного, а также точные оценки трудоемкости такого алгоритма и объема используемой им памяти.
8. Доказательство теоремы 2.1 об иррациональности действительных чисел, определяемых рядом \( \alpha=\sum_{k=0}^{\infty}\frac{x_k}{k!} \) для периодической последовательности рациональных чисел \( (x_{k})^{\infty}_{k=0} \).
9. Доказательство утверждений (см. теоремы 2.4 и 2.5) о совпадении разложений в систематическую дробь, а также доказательство критерия (см. теорему 2.6) нормальности действительных чисел из рассматриваемых классов.

*Достоверность* полученных результатов обеспечивается ...
Результаты находятся в соответствии с результатами, полученными другими авторами.

Достоверность полученных результатов обеспечивается строгими математическими выкладками и доказательствами, апробацией на конференциях и семинарах, а также публикациями в рецензируемых научных журналах.
Результаты других авторов, упомянутые в тексте диссертации, отмечены ссылками на соответствующие публикации.

*Апробация работы*.
Основные результаты работы докладывались на: перечисление основных конференций, симпозиумов и т.п.
1. Семинар научного руководителя Московского института электроники и математики им. А.Н. Тихонова федерального государственного автономного образовательного учреждения высшего образования "Национальный исследовательский университет 'Высшая школа экономики'", г.\nbsp{}Москва, 2022 г.
2. Международный симпозиум "Современные тенденции в криптографии CTCrypt", г. Суздаль, 2018, г.\nbsp{}Казань, 2015\nbsp{}г.
3. Семинар "Математические методы криптографического анализа" кафедры информационной безопасности факультета вычислительной математики и кибернетики МГУ им. М.В.Ломоносова, г.\nbsp{}Москва, 2023 г., 2018 г.


*Личный вклад*. Автор принимал активное участие ...

*Публикации*.
Основные результаты по теме диссертации изложены в XX печатных изданиях, X из которых изданы в журналах, индексируемых в Web of Science, Scopus, RSCI и рекомендованных ВАК Минобрнауки России, из них XX\nbsp{}--- в изданиях, индексируемых в Web of Science, Scopus, RSCI.
Также автором получены XX свидетельств о государственной регистрации программ для ЭВМ.

*Объем и структура работы*.
Диссертация состоит из\nbsp{}введения,
четырех глав, заключения, одного приложения, списка литературы.
Полный объём диссертации составляет XXX страниц с\nbsp{}XX\nbsp{}рисунками и\nbsp{}XX\nbsp{}таблицами.
Список литературы содержит XXX\nbsp{}наименований.

* Сведения из теории линейных блоковых кодов
#+name: ch:linear-codes
Теория кодов, исправляющих ошибки, обязана своему появлению классическим работам Клода Шеннона.
В 50-е года XX века в связи с появлением работ Шеннона возник большой поток исследований,
посвящённых построению эффективных схем кодирования информации для передачи по реальным каналам с шумами.
С практической точки зрения существенные ограничения на все схемы кодирования и декодирования дискретных данных накладываются не шенноновской пропускной способностью, а сложностью самого декодера.

Новый подход к решению проблемы был найден в фундаментальных работах Киясу (1957) и Слепяна (1956), Рида и Соломона (1960), Хоквингема (1959), Боуза и Чоудхури (1960), Горенстейна и Цирлера (1961) и Питерсона (1961).
Именно работы этих исследователей фактически положили начало новой области математики\nbsp{}--- теории кодов, исправляющих ошибки.

Коды, исправляющие ошибки, можно рассматривать фактически над любым алфавитом.
Однако наиболее удобным оказывается алфавит, представляющий собой поле Галуа.
В этом случае можно свести задачи кодирования и декодирования к решению алгебраических уравнений.
Развитие компьютерной техники привело к тому, что наиболее часто стали рассматриваться коды над алфавитом\nbsp{}--- полем Галуа характеристики \(2\).

В самом общем случае кодом над некоторым алфавитом называется любое множество слов над этим алфавитом.
Но такое понимание кода является очень широким, а поэтому сложным для исследования.
В силу этого обычно исследуются коды, обладающие некоторым свойством.
Например, таким свойством является линейность.
Линейные коды, т.\nbsp{}е. коды, которые образуют линейное пространство над полем Галуа, на сегодняшний день изучены наиболее полно по сравнению с другими классами кодов.
Именно такие коды находят приложения в современной криптографии.

** Базовые термины и определения
#+name: sec:definitions

Рассмотрим конечное поле \(\mathbb{F}_q\) порядка \(q\).
Тогда векторное пространство размерности \(n\) над полем \(\mathbb{F}_q\) будем обозначать через \(\mathbb{F}^n_q\).
Элементами \( \mathbb{F}^{n}_{q} \), как это принято в теории кодов, исправляющих ошибки, являются векторы-строки \( \vect{v} = \left(v_{1}, v_{2}, \dotsc, v_{n}\right) \).

Через \( \mathbb{F}^{k \times n}_{q} \) обозначим множество всех \( (k \times n) \)-матриц \( \matr{M} \) с элементами из поля \( \mathbb{F}_{q} \).
Так как элементами \( \mathbb{F}^{n}_{q} \) являются векторы строки, поэтому если \( \vect{m}_1, \vect{m}_2, \dotsc ,\vect{m}_{n}\in \mathbb{F}^{k}_{q} \), то запись вида
\[ \matr{M}=\left(\vect{m}^{\top}_{1}, \vect{m}^{\top}_{2}, \dotsc, \vect{m}^{\top}_{n}\right) \]
будет обозначать \( (k \times n) \)-матрицу, столбцом с номером \( j \) которой будет вектор-строка \( \vect{m}_j \), \( 1\le j\le n \).
Соответственно запись вида
\[ \matr{M}= \begin{pmatrix}
             \vect{m}_{1}\\
             \vect{m}_{2}\\
             \vdots\\
             \vect{m}_{n}
             \end{pmatrix} = \left(\vect{m}^{\top}_{1}, \vect{m}^{\top}_{2}, \dotsc, \vect{m}^{\top}_{n}\right)^{\top} \]
означает \( (n \times k) \)-матрицу, строкой с номером \( i \) которой является вектор \( \vect{m}_i \), \( 1\le i\le k \).

Введем естественным способом скалярное произведение векторов пространства \(\mathbb{F}^n_q\).

Пусть \(\vect{x}=(x_1,x_2,\ldots, x_n)\) и \(\vect{y}=(y_1,y_2,\ldots,y_n)\)\nbsp{}--- векторы над полем \(\mathbb{F}_q\).
Тогда скалярным произведением векторов \(\vect{x}\) и \(\vect{y}\) называется элемент \(\left\langle \vect{x}, \vect{y} \right\rangle\in \mathbb{F}_q\)
\[
\left\langle\vect{x}, \vect{y}\right\rangle
\stackrel{\mathrm{def}}{=} x_1\cdot y_1 + x_2\cdot y_2 + \ldots + x_n\cdot y_n.
\]
Здесь «\(+\)» и «\(\cdot\)»\nbsp{}--- соответственно операции сложения и умножения в поле \(\mathbb{F}_q\).
Векторы, скалярное произведение которых равно нулю, принято называть ортогональными.

Введем на пространстве \(\mathbb{F}^n_q\) метрику Хемминга.
Заметим, что обычно в криптографии рассматриваются коды именно в этой метрике.
Хотя в последнее время в различных приложениях появился интерес к линейным кодам в ранговой метрике и в метрике Ли.

Весом Хэмминга \(\operatorname{wt}_H(\vect{x})\) или просто весом \(\operatorname{wt}(\vect{x})\) вектора \(\vect{x}\in \mathbb{F}^n_q\) называется число ненулевых координат этого вектора.

Расстоянием Хэмминга \(\operatorname{d}_H(\vect{x},\vect{y})\) или просто расстоянием \(\operatorname{d}(\vect{x},\vect{y})\) между двумя векторами \(\vect{x}\in \mathbb{F}^n_q\) и \(\vect{y}\in \mathbb{F}^n_q\) называется число координат, в которых эти векторы отличаются, т.е. \(\operatorname{d}_H(\vect{x},\vect{y})=\operatorname{wt}_H(\vect{x}-\vect{y})\).

Для натурального числа \( n \) через \( \str{S}_{n} \) обозначим симметрическую группу, т.\nbsp{}е. группу подстановок \( \elt{\sigma} \) на множестве \( [\![n]\!] \stackrel{\mathrm{def}}{=} \left\{1,2, \dotsc, n\right\} \).

Определим действие группы \( \str{S}_{n} \) на векторы \( \vect{x}\in \mathbb{F}^{n}_{q} \).
Пусть \(\elt{\sigma}\)\nbsp{}--- подстановка из \(\str{S}_{n}\), а \(\vect{x}=(x_1,x_2,\ldots,x_n)\)\nbsp{}--- вектор с элементами из \(\mathbb{F}_q\).
Подстановка \(\elt{\sigma}\) переводит вектор \(\vect{x}\) в вектор \(\vect{x}^{\elt{\sigma}}\), построенный по правилу
\[\vect{x}^{\elt{\sigma}}\stackrel{\mathrm{def}}{=}(x_{\elt{\sigma}^{-1}(1)},x_{\elt{\sigma}^{-1}(2)},\ldots,x_{\elt{\sigma}^{-1}(n)}).\]
Обратим внимание, что координаты вектора \( \vect{x} \) переставляются в соответствии с обратной подстановкой \( \elt{\sigma}^{-1} \), а не \( \elt{\sigma} \).
Такое определение мотивировано тем, что рассматриваются векторы строки, а не векторы столбцы и для согласования действия подстановок с групповой операцией требуется определять это действие описанным способом.

Каждой подстановке \( \elt{\sigma}\in \str{S}_{n}\) можно однозначно сопоставить квадратную \((n\times n)\)-матрицу \(\matr{\sigma}=(s_{ij})_{1\le i,j\le n}\in \mathbb{F}^{n \times n}_{q}\), состоящую только из элементов \( 0 \) и \( 1 \), следующим образом.
Элемент \(s_{ij}=1\), если и только если \(\elt{\sigma}(j)=i\).
Все остальные элементы равны \(0\).
Матрица \(\matr{\sigma}\) называется перестановочной матрицей.

Легко видеть, что действие подстановки \(\elt{\sigma}\) на \(\mathbb{F}^n_q\) можно задать через матричное умножение следующим образом:
\( \vect{x}^{\elt{\sigma}}=\vect{x}\cdot \matr{\sigma}.\)

Действие \( \str{S}_{n} \) на \(\mathbb{F}^n_q\) линейно, т.\nbsp{}е. для любых \(\vect{x}, \vect{y}\in \mathbb{F}^n_q\) и любой подстановки \( \elt{\sigma} \) выполняется равенство \((\vect{x}+\vect{y})^{\elt{\sigma}}=\vect{x}^{\elt{\sigma}}+\vect{y}^{\elt{\sigma}}\).

Пусть \(U\subseteq \mathbb{F}^n_q\).
Тогда \(U^{\elt{\sigma}}\)\nbsp{}--- это множество, состоящее из векторов \(\vect{x}^{\elt{\sigma}}\in \mathbb{F}^n_q\), где \(\vect{x}\in U\).
В силу того, что действие группы \(S_n\) на \(\mathbb{F}^n_q\) линейно, то \(U^{\elt{\sigma}}\)\nbsp{}--- линейное подпространство \(\mathbb{F}^n_q\), если и только если \(U\) является линейным подпространством \(\mathbb{F}^n_q\).

Обозначим через \( \mathbb{F}_{q}[x_1,x_{2}\dotsc, x_{k}] \) кольцо многочленов \( f(x_1, x_2,\dotsc, x_{k}) \) с коэффициентами из поля \( \mathbb{F}_{q} \).
Если \( \vect{x}=(x_1,x_2, \dotsc, x_{k}) \)\nbsp{}--- вектор-столбец формальных переменных, то для краткости вместо \( \mathbb{F}_{q}[x_1,\dotsc, x_{k}] \) будем писать \( \mathbb{F}_{q}[\vect{x};k] \) и вместо \( f(x_1,x_2, \dotsc, x_k) \)\nbsp{}--- \( f(\vect{x}^{\top}) \).

Зафиксируем некоторый кортеж (упорядоченное множество) \( U= \left(\vect{u}_1, \vect{u}_2, \dotsc, \vect{u}_{n}\right) \) векторов из \( \mathbb{F}^k_{q} \), т.е. \( U\subseteq \mathbb{F}^{k}_{q} \) и \( \vect{u}_i=(u_{i,1}, u_{i,2}, \dotsc, u_{i,k})\in \mathbb{F}^{k}_{q} \) для всех \( i=1,2, \dotsc, n \).
Определим линейный оператор \( \operatorname{ev}_{U}: \mathbb{F}_{q}[\vect{x};k] \rightarrow  \mathbb{F}^{n}_{q}\), который каждому многочлену \( f(x_1, x_2, \dotsc, x_{k}) \) ставит в соответствие его вектор значений на элементах \( U \), т.е.
\[ f(x_1,x_2, \dotsc, x_k) \rightarrow \left(f(\vect{u}^{\top}_{1}), f(\vect{u}^{\top}_{2}), \dotsc, f(\vect{u}^{\top}_{n})\right)\in \mathbb{F}^{n}_{q}, \]
где \( f(\vect{u}^{\top}_i) \stackrel{\mathrm{def}}{=} f(u_{i,1}, u_{i,2}, \dotsc, u_{i,k})\in \mathbb{F}^{n}_{q} \)\nbsp{}--- значение полинома \( f \) на векторе \( \vect{u}_{i} \), \( i=1,2, \dotsc, n \).

Пусть \(\matr{G} \in \mathbb{F}_{q}^{k \times n} \) и \( \matr{G} = \left(\vect{g}^{\top}_{1}, \vect{g}^{\top}_{2}, \dotsc, \vect{g}^{\top}_{n}\right) \), где \( \vect{g}_{j}= \left(g_{1,j}, g_{2,j}, \dotsc, g_{k,j}\right) \)\nbsp{}--- столбец с номером \( j \), \( j=1,2, \dotsc, n \), матрицы \( \matr{G} \).
Тогда \( \matr{G} \) можно рассматривать как кортеж ее столбцов и поэтому будет определено отображение \( \operatorname{ev}_{\matr{G}} \), которое многочлену \( f\in \mathbb{F}_{q}[\vect{x};k] \) ставит в соответствие вектор значений \( f \) на столбцах матрицы \( \matr{G} \), т.е.
\[ \operatorname{ev}_{\matr{G}}\!\left(f\right)= \left(f(\vect{g}^{\top}_{1}), f(\vect{g}^{\top}_{2}), \dotsc, f(\vect{g}^{\top}_{n})\right)\in \mathbb{F}^{n}_{q}. \]

Определим теперь действие полной линейной группы \( \str{GL}_{k}(q) \) на кольце \( \mathbb{F}_{q}[\vect{x};k] \).
Если \( \elt{A}\in \str{GL}_{k}(q) \), а через \( \matr{A}\in \mathbb{F}^{k \times k}_{q} \) обозначена невырожденная \( (k \times k) \)-матрица, соответствующая элементу \( \elt{A} \), то каждому многочлену \( f\in \mathbb{F}_{q}[\vect{x};k] \) поставим в соответствие многочлен \( f^{\elt{A}}(\vect{x}^{\top}) \) по правилу
\[ f^{\elt{A}}(\vect{x}^{\top}) \stackrel{\mathrm{def}}{=} f(\matr{A}\cdot\vect{x}^{\top}). \]

Аналогично можно определить действие полной аффинной группы \( \str{GA}_{k}(q) \) на \( \mathbb{F}_{q}[\vect{x};k] \).
Если \( (\elt{A}, \elt{a})\in \str{GA}_{k}(q) \), и пусть \( (\matr{A}\in \mathbb{F}^{k \times k}_{q}, \vect{a}\in \mathbb{F}^{k}_{q}) \)\nbsp{}--- соответствующие элементу \( (\elt{A},\elt{a}) \) невырожденная матрица и вектор, то каждому \( f\in \mathbb{F}_{q}[\vect{x};k] \) сопоставим многочлен \( f^{(\elt{A}, \elt{a})}(\vect{x}^{\top}) \) по правилу
\[ f^{(\elt{A}, \elt{a})}(\vect{x}^{\top}) \stackrel{\mathrm{def}}{=} f(\matr{A}\cdot \vect{x}^{\top}+\vect{a}^{\top}). \]

Обозначим через \( [\![n]\!] \)\nbsp{}--- множество их первых \( n \) натуральных чисел, т.е. \( [\![n]\!] \stackrel{\mathrm{def}}{=} \left\{1,2, \dotsc, n\right\} \).

Если \( T\subseteq [\![n]\!] \) и \( \vect{v}= \left(v_{1}, v_{2}, \dotsc, v_{n}\right)\in \mathbb{F}_{q}^{n} \), то через \( \vect{v}\vert_{T} \) обозначим подвектор вектора \( \vect{v} \), составленный из координат с номерами из множества \( T \), т.е. \( \vect{v}\vert_{T}= \left( v_{i},\ i\in T\right)\in \mathbb{F}_{q}^{n-|T|}\).

Далее определим еще два вектора: \( \vect{v}_{\setminus T} \) и \( \vect{v}_{T} \).
Вектор \( \vect{v}_{\setminus T}\in \mathbb{F}_{q}^{n-|T|} \) имеет длину \( n-|T| \) и состоит из тех координат вектора \( \vect{v} \), номера которых не лежат во множестве \( T \), т.е. \( \vect{v}_{\setminus T}=\vect{v}\vert_{[\![n]\!]\setminus T} \) и он получается из \( \vect{v} \) удалением координат с номерами из множества \( T \).
Вектор \( \vect{v}_{T}\in\mathbb{F}_{q}^{n} \) имеет ту же длину, что \( v \), и получается из \( \vect{v} \) обнулением координат, имеющих номера из множества \( T \).
Получается, что если \( \vect{v}_{T}= \left(u_{1}, u_{2}, \dotsc, u_{n}\right) \), то для всех \( i\in [\![n]\!]\setminus T \) выполняется равенство \( u_{i}=v_{i} \), а для \( i\in T \)\nbsp{}--- равенство \( u_{i}=0\), т.е. \( (\vect{v}_{T})\vert_{T}=\vect{0}^{|T|} \) и \( (\vect{v}_{T})_{\setminus T}=v_{\setminus T} \).

Аналогичную систему обозначений перенесем и на матрицы.

** Линейные коды
#+name: sec:linear-codes-basics

Линейные коды впервые появились в работах Киясу и Слепяна.
В силу того, что эти коды образуют такую хорошо изученную структуру как линейное пространство, они стали основным объектом исследований.
Линейные коды могут быть определены над любым конечным полем.

#+caption: Определение линейного блокового кода длины n
#+name: def:ncode
#+begin_definition
Линейное подпространство \(\code{C}\) пространства \(\mathbb{F}^n_q\) называется \([n]_q\)-кодом.
При этом \(n\) называется длиной кода \(\code{C}\).
Если \(q=2\), то \([n]_2\)-код будем называть просто \([n]\)-кодом.
#+end_definition

#+caption: Определение линейного кода размерности k
#+name: def:nkcode
#+begin_definition
\([n]_q\)-код \(\code{C}\) будем называть \([n,k]_q\)-кодом, если \(\code{C}\) имеет размерность \(k\) как подпространство линейного пространства \(\mathbb{F}^n_q\).
При этом число \(k\) называется размерностью кода \(\code{C}\).
#+end_definition

В силу того, что линейный \([n,k]_q\)-код \(\code{C}\) является линейным конечномерным пространством, то в коде всегда можно выбрать конечный базис векторов этого пространства.
При этом любой вектор из \(\code{C}\) можно представить как линейную комбинацию векторов базиса.
Это замечание подводит к определению порождающей матрицы кода \(\code{C}\).

#+caption: Определение порождающей матрицы кода
#+name: def:generator-matrix
#+begin_definition
Матрица \( \matr{G} \) размера \((k\times n)\) с элементами из \(\mathbb{F}_q\), строками которой являются векторы базиса \([n,k]_q\)-кода \(\code{C}\), называется порождающей матрицей кода \(\code{C}\).
При этом про саму матрицу \(\matr{G}\) будем говорить, что она порождает код \(\code{C}\).
#+end_definition

#+caption: Задание кода через линейные комбинации строк матрицы
#+name: def:generating-matrix
#+begin_definition
Будем говорить, что \((m\times n)\)-матрица \(\matr{G}\) c элементами из \(\mathbb{F}_q\) охватывает код \(\code{C}\), если множество всех возможных линейных комбинаций строк матрицы \(\matr{G}\) совпадает с кодом \(\code{C}\), т.е.
\[ \code{C}=\{\vect{a}\matr{G}\mid\vect{a}\in \mathbb{F}^{m}_{q}\}. \]

Получается, что охватывающая матрица кода в общем случае имеет не полный ранг.
#+end_definition

Если \((k\times n)\)-матрица \(\matr{G}\) охватывает \([n,k]_q\)-код \(\code{C}\), то она является его порождающей матрицей.

Отметим общеизвестный факт.

#+caption: Критерий эквивалентности порождающих матриц
#+name: prop:the-same-generator
#+begin_proposition
Матрицы \(\matr{G}_1\) и \(\matr{G}_2\) размера \((k\times n)\) с элементами из поля \(\mathbb{F}_q\) порождают один и тот же кода \(\code{C}\), если и только если существует такая невырожденная двоичная матрица \(\matr{M}\), что \(\matr{G}_1=\matr{M}\cdot\matr{G}_2\).
#+end_proposition

На основании утверждения\nbsp{}[[prop:the-same-generator]] можно переходить от одной порождающей матрицы кода \(\code{C}\) к другой, просто выполняя линейные операции над строками исходной матрицы.

#+caption: Число порождающих матриц заданного кода
#+name: prop:number-of-generator-matrices
#+begin_proposition
Число порождающих матриц \([n,k]_q\)-кода равно
\[
(q^k-1)(q^k-q)\cdots (q^{k}-q^{k-1}).
\]
#+end_proposition

#+caption: Число различных линейных кодов параметров n k
#+begin_proposition
Число различных \([n,k]_q\)-кодов равно
\[
\frac{(q^n-1)(q^n-q)\cdots (q^n-q^{k-1})}{(q^k-1)(q^k-q)\cdots (q^{k}-q^{k-1})}.
\]
#+end_proposition

#+caption: Информационное окно
#+name: def:inform-set
#+begin_definition
Пусть \( I \subseteq [\![n]\!] \).
Традиционно множество \( I \) называется информационным окном или информационным множеством \( [n,k]_{q} \)-кода \( \mathcal{C} \) с порождающей матрицей \( \matr{G} \), если \( |I|=k \) и подматрица \( \matr{G}\vert_{I} \), составленная из столбцов \( \matr{G} \) с номерами из \( I \), является невырожденной.
#+end_definition

Заметим, что при фиксированном информационном окне \( I \) кода \( \mathcal{C} \) с порождающей матрицей \( \matr{G} \) существует единственная порождающая матрица \( \matr{G}' \) кода \( \mathcal{C} \), у которой в позициях с номерами из \( I \) стоит единичная \( (k \times k) \)- матрица \( \matr{I}_k \), т.е. \( \matr{G}'_{I} = \matr{I}_k \).
Приходим к следующему важному определению.

#+caption: Определение систематической порождающей матрицы
#+name: def:systematic-matrix
#+begin_definition
Матрица \( \matr{G}\in \mathbb{F}^{k \times n}_{q} \) называется систематической, если она имеет вид
\[ \matr{G} = \left(\matr{I}_k\vert \matr{G}'\right), \]
где \( \matr{I}_k \)\nbsp{}--- единичная \( (k \times k) \)-матрица, а \( \matr{G}'\in \mathbb{F}^{(n-k) \times n}_{q} \)\nbsp{}--- произвольная \( ((n-k) \times k) \)-матрица.
#+end_definition

Заметим, что в общем случае у линейного кода может не быть систематической порождающей матрицы, однако у него всегда существует порождающая матрица, которая отличается от систематической только перестановкой столбцов.
Иногда в литературе такую порождающую матрицу из называют полусистематической или почти систематической.

Таким образом, матрица \(\matr{G} = \left(\vect{g}^{\top}_{1}, \vect{g}^{\top}_{2}, \dotsc, \vect{g}^{\top}_{n}\right)\in \mathbb{F}^{k \times n}_{q}\) называется полусистематической, если существуют такие номера столбцов \( 1\le j_1< j_2 < \dotsb < j_{k}\le n \), что
\[
\left(\vect{g}^{\top}_{j_1}, \vect{g}^{\top}_{j_2}, \dotsc, \vect{g}^{\top}_{j_k}\right) = \matr{I}_k,
\]
где \(\matr{I}_{k}\)\nbsp{}--- единичная матрица размера \(k\).
Если \( \matr{G} \) порождает код \( \mathcal{C} \), то в этом случае множество \( I=\left\{j_1,j_2, \dotsc, j_k\right\} \) будет информационным.
Но чтобы не вводить дополнительных сущностей такие матрицы тоже будем называть систематическими, уточняя информационное множество.

Если \([n,k]_q\)-код \(\code{C}\) порождается матрицей \(\matr{G}\), то для любого кодового вектора \(\vect{x}\) кода \(\code{C}\) найдется вектор \(\vect{a}\) длины \(k\) с элементами из \(\mathbb{F}_q\) такой, что
\[
\vect{x}=\vect{a}\cdot \matr{G}.
\]

Значит для линейного кода \(\code{C}\) с порождающей матрицей \(\matr{G}\) можно определить процедуру кодирования (кодер) \(k\)-мерных векторов:
\[
\vect{a}\in \mathbb{F}^{k}_{q} \rightarrow \vect{a}\cdot \matr{G} \in \mathbb{F}^{n}_{q}.
\]

Фактически задание порождающей матрицы \(\matr{G}\) кода \(\code{C}\) определяет свой кодер.

#+caption: Определение систематического кодера
#+begin_definition
Про код \(\code{C}\), порождаемый систематической матрицей (в узком смысле) \(\matr{G}=(\matr{I}_{k}\vert \matr{G}')\) говорят, что он имеет систематический кодер:
\[
\vect{a}=(a_1,\ldots,a_k) \rightarrow \vect{v}=(a_1,\ldots,a_k,\vect{a}\cdot \matr{G}').
\]
Коды, имеющие систематический кодер, называются систематическими.
#+end_definition

#+caption: Определение проверки на чётность кода
#+begin_definition
Проверкой на четность \([n]_q\)-кода \(\code{C}\) называется такой вектор \(\vect{h}\in \mathbb{F}^n_q\), что для всех кодовых векторов \(\vect{c}\in \code{C}\) выполнено равенство
\[
\left\langle\vect{h},\vect{c}\right\rangle =0.
\]
Если вектор \(\vect{h}=(11\ldots 1)\) является проверкой на чётность кода \(\code{C}\), то он называется общей проверкой на четность кода \(\code{C}\).
#+end_definition

#+caption: Связь порождающей матрицы и проверки на чётность
#+begin_proposition
Если код \(\code{C}\) задан своей порождающей матрицей \(\matr{G}\), а \(\vect{h}\)\nbsp{}--- его проверка на четность, то
\[
\matr{G} \cdot \vect{h}^{\top} =\vect{0},\quad \vect{h} \cdot \matr{G}^{\top}=\vect{0}.
\]
#+end_proposition

Множество всех проверок на четность кода \(\code{C}\) является линейным подпространством \( \mathbb{F}^{n}_{q} \).
Приходим к следующему определению.

#+caption: Определение дуального кода
#+begin_definition
Дуальным кодом \(\code{C}^\perp\) к \([n,k]_q\)-коду \(\code{C}\) называется код, который содержит все проверки на четность кода \( \mathcal{C} \).
Код \( \mathcal{C}^{\perp} \) состоит из всех векторов \( \mathbb{F}_{q} \), ортогональных каждому кодовому слову \(\code{C}\), т.\nbsp{}е.
\[
\code{C}^\perp=\left\{\vect{b}\in \mathbb{F}^n_q\;\middle\vert\; (\vect{b},\vect{c})=0\quad \forall\, \vect{c}\in \code{C}\right\}.
\]
#+end_definition

#+caption: Свойства дуального кода
#+name: prop:dual-code-properties
#+begin_proposition
Если \( \mathcal{C} \)\nbsp{}--- \( [n,k]_q \) код, то
1. код \( \mathcal{C}^{\perp} \) является \( [n, n-k]_{q} \)-кодом;
2. верно равенство \( \left(\code{C}^{\perp}\right)^{\perp}=\mathcal{C} \), т.\nbsp{}е. код \( \mathcal{C} \) является дуальным к своему дуальному коду.
#+end_proposition

Из утверждения\nbsp{}[[prop:dual-code-properties]] следует, что если \( \matr{G}^{\perp} \)\nbsp{}--- порождающая матрица кода \( \mathcal{C} \), то каждое кодовое слово \( \vect{c}\in \mathcal{C} \) удовлетворяет соотношению ортогональности \( \matr{G}^{\perp}\cdot \vect{c}^{\top} = \vect{0} \), и при этом, если какой-то вектор \( \vect{x}\in \mathbb{F}^{n}_{q} \) является решением той же системы однородных линейных уравнений, то он будет кодовым словом кода \( \mathcal{C} \).
Тем самым можно говорить, что критерием принадлежности вектора \( \vect{x} \) коду является выполнение равенства \( \matr{G}^{\perp}\cdot \vect{x}^{\top} = \vect{0} \).

#+caption: Определение проверочной матрицы
#+begin_definition
Матрица \(\matr{H}\in \mathbb{F}^{r \times n}_{q}\), для которой выполняется равенство
\[ \matr{H}\cdot \vect{c}^{\top}=\vect{0}, \]
если и только если \( \vect{c}\in \mathcal{C} \) называется проверочной матрицей кода \( \mathcal{C} \).
Другими словами, проверочная матрица охватывает код \( \mathcal{C}^{\perp} \) и имеет ранг \( n-k \).
#+end_definition

Отметим, что в определении проверочной матрицы мы не требуем, чтобы она имела максимальный ранг.
Более того, для некоторых кодов проще построить проверочную матрицу, которая обладает некоторой избыточностью, чем матрицу максимального ранга.

#+caption: Ортогональность порождающей и проверочной матриц
#+begin_proposition
Если \(\matr{G}\) и \(\matr{H}\) соответственно порождающая и проверочная матрица \( [n,k]_{q} \)-кода \(\code{C}\), то выполнены равенства
\[
\matr{H}\matr{G}^{\top}=\vect{0}_{r \times k},\ \ \matr{G}\matr{H}^{\top}=\vect{0}_{k \times r}.
\]
#+end_proposition

Очевидно, что если \(\matr{G}=(\matr{I}_k\vert \matr{G}')\)\nbsp{}--- систематическая порождающая матрица кода \( \mathcal{C} \), то матрица \( \matr{H}=(-\matr{G}'^{\top}\vert \matr{I}_{n-k}) \) будет проверочной матрицей того же кода.

#+caption: Критерий эквивалентности проверочных матриц
#+name: prop:the-same-parity
#+begin_proposition
Матрицы \(\matr{H}_1\in \mathbb{F}^{r \times n}_{q}\) и \(\matr{H}_2\in \mathbb{F}^{r\times k}_{q}\) являются проверочными матрицами одного и того же кода \(\code{C}\), если и только если существует такой \( \elt{A}\in \elt{GL}_r(q) \), что выполняется равенство \(\matr{H}_1=\matr{A}\cdot\matr{H}_2\).
#+end_proposition

Итак, для задания любого линейного кода \( \mathcal{C} \) достаточно указать либо его порождающую матрицу \( \matr{G} \), либо проверочную матрицу \( \matr{H} \).

Иногда код может содержаться в своем дуальном коде, а иногда может с ним совпадать.
Для таких кодов в теории кодирования существуют специальные названия.

#+caption: Определение самодуальных и слабо самодуальных кодов
#+name: def:self-dual
#+begin_definition
Код \(\code{C}\) называется самоортогональным (или слабо самодуальным), если выполняется включение \( \mathcal{C}\subseteq \mathcal{C}^{\perp} \).
Самоортогональный код является самодуальным (или строго самодуальным), если включение становится равенством, т.е. \( \mathcal{C}=\mathcal{C}^{\perp} \).
#+end_definition

Длина и размерность являются фундаментальными параметрами любого кода, характеризующими этот код как линейное пространство.

Введем в рассмотрение третий фундаментальный параметр линейного кода, связанный с метрикой Хемминга и который характеризует способность кода исправлять ошибки.

#+caption: Определение кодового расстояния
#+name: def:code-distance
#+begin_definition
Минимальным расстоянием линейного кода \(\code{C}\) называется число \(d\), равное минимальному расстоянию между различными кодовыми словами кода \(\code{C}\), то есть
\begin{equation*}
d=\min_{\begin{subarray}{l}\vect{c},\vect{b}\in \mathcal{C},\\\vect{c}\neq\vect{b}\end{subarray}}\operatorname{d}(\vect{c},\vect{b}) = \min_{\begin{subarray}{l}\vect{c},\vect{b}\in \mathcal{C},\\\vect{c}\neq\vect{b}\end{subarray}}\operatorname{wt}(\vect{c}-\vect{b}).
\end{equation*}
Кодовое расстояние линейного кода \(\code{C}\) равно минимальному весу ненулевых кодовых слов кода \(\code{C}\):
\begin{equation*}
d=\min_{\vect{c}\in \code{C},\;\vect{c}\neq \vect{0}}\operatorname{wt}(\vect{c}).
\end{equation*}
#+end_definition

В дальнейшем, если \( [n,k]_{q} \)-код имеет кодовое расстояние \(d\), то будем называть такой код \([n,k,d]_{q}\)-кодом.

Кодовое расстояние кода связано с линейно независимыми столбцами проверочной матрицы кода.

#+caption: Критерий минимального расстояния по столбцам проверочной матрицы
#+name: prop:distance-parity-checks
#+begin_proposition
Пусть \(\matr{H}\)\nbsp{}--- проверочная матрица кода \(\code{C}\).
Тогда
1. если код \(\code{C}\) имеет минимальное расстояние \(d\), то в матрице \( \matr{H} \) найдется система из \( d \) линейно зависимых столбцов;
2. если любая система из не более, чем  \(d-1\) столбца матрицы \(\matr{H}\) линейно независимы, но минимальное расстояние кода \( \mathcal{C} \) больше или равно \(d\).
#+end_proposition

Другой важнейшей характеристикой кода \(\code{C}\) является его спектр весов.

#+caption: Определение спектра весов кода
#+name: def:weight-spectrum
#+begin_definition
Спектром весов \([n]_q\)-кода \(\code{C}\) называется вектор
\[
\vect{A}(\code{C})=(A_0,A_1,\ldots,A_{n})\in\mathbb{N}^{n},
\]
у которого координата \(A_i\), \(i=0\ldots n\), равна количеству кодовых слов кода \(\code{C}\) веса Хемминга \(i\), т.е.
\[
A_{i}=\left|\left\{\vect{c}\in\code{C}|\ \operatorname{wt}(\vect{c})=i\right\}\right|,\ \ i=0\ldots n.
\]
#+end_definition


* RAW :noexport:

#+caption: Формулировка задачи декодирования по минимальному расстоянию
#+name: def:decode-problem-form-1
#+begin_definition
Пусть \(\code{C}\)\nbsp{}--- некоторый \([n,k]_{q}\)-код.
Задачей декодирования вектора \(\vect{y}\in \mathbb{F}^n_q\) называется задача поиска такого вектора \(\boldsymbol{c}\in\code{C}\), что
\[
\operatorname{d}(\boldsymbol{c},\vect{y})=\min_{\boldsymbol{c}'\in\code{C}}\operatorname{d}(\boldsymbol{c}',\vect{y}).
\]
#+end_definition

Так как по определению\nbsp{}\ref{def:hamming-distance} верно равенство \(\operatorname{d}(\vect{x},\vect{y})=\operatorname{wt}(\vect{y}-\vect{x})\), то можно дать следующее определение, эквивалентное определению\nbsp{}\ref{def:decode-problem-form-1}.

#+caption: Эквивалентная формулировка задачи декодирования по весу ошибки
#+begin_definition
Задачей декодирования вектора \(\vect{y}\in \mathbb{F}^n_q\) называется задача поиска такого вектора \(\boldsymbol{c}\in\code{C}\), что
\[
\operatorname{wt}(\vect{y} - \boldsymbol{c})=\min_{\boldsymbol{c}'\in\code{C}} \operatorname{wt}(\vect{y} - \boldsymbol{c}').
\]
#+end_definition

Если положить \(\boldsymbol{e}=\vect{y} - \boldsymbol{c}\) , то по своему смыслу \(\boldsymbol{e}\)\nbsp{}--- вектор ошибок минимально возможного веса для вектора \(\boldsymbol{c}\).
Поэтому задача декодирования может быть сформулирована в следующем эквивалентном виде.

#+caption: Задача декодирования как поиск минимального вектора ошибок
#+name: def:decode-task-form-2
#+begin_definition
Задачей декодирования \(\mathrm{DEC}_{\code{C}}(\vect{y})\) вектора \(\vect{y}\in \mathbb{F}^n_q\) называется задача поиска такого вектора \(\boldsymbol{e}\in \mathbb{F}^n_q\), что
- *1):* вектор \(\vect{y}-\boldsymbol{e}\in \code{C}\), т.е. является кодовым словом;
- *2):* вектор \(\boldsymbol{e}\) имеет минимально возможный вес Хемминга среди всех векторов \(\boldsymbol{e}\), обеспечивающих выполнение условия 1).

Или, что тоже самое,
\[
\vect{y}-\boldsymbol{e}\in\code{C},\ \ \operatorname{wt}(\boldsymbol{e})\rightarrow \min.
\]
В теории кодирования вес вектора ошибок \(\boldsymbol{e}\) принято называть кратностью.
#+end_definition

Для любого вектора \(\vect{y}\in \mathbb{F}^n_q\) задача декодирования \(\mathrm{DEC}_{\code{C}}(\vect{y})\) имеет хотя бы одно решение.
Действительно, если \(\boldsymbol{c}\in\code{C}\)\nbsp{}--- любой кодовый вектор, то \(\boldsymbol{e}=\vect{y}-\boldsymbol{c}\) обеспечивает выполнение условия 1) в определении\nbsp{}\ref{def:decode-task-form-2}, а значит для поиска решения нужно перебрать все векторы \(\boldsymbol{c}\in\code{C}\) и найти такой, который даёт минимальный вектор ошибок \(\boldsymbol{e}\).
Однако существование решения задачи декодирования \(\mathrm{DEC}_{\code{C}}(\vect{y})\) не гарантирует его единственность.

#+caption: Определение исправления конкретной ошибки
#+name: def:code-correct-fix-error
#+begin_definition
Говорят, что код \(\code{C}\) исправляет ошибку \(\boldsymbol{e}\), если для любого кодового слова \(\boldsymbol{c}\in\code{C}\) задача декодирования \(\mathrm{DEC}_{\code{C}}(\boldsymbol{c}+\boldsymbol{e})\) имеет единственное решение\nbsp{}--- \(\boldsymbol{e}\).
#+end_definition

#+caption: Определение исправления ошибок фиксированной кратности
#+name: def:code-correct-t-errors
#+begin_definition
Говорят, что код \(\code{C}\) исправляет ошибки кратности \(t\in\mathbb{Z}_{\ge 0}\), если он исправляет все ошибки \(\boldsymbol{e}\) веса Хемминга \(t\).
#+end_definition

#+caption: Определение исправления не более t ошибок
#+name: def:code-correct-errors
#+begin_definition
Говорят, что код \(\code{C}\) исправляет \(t\in\mathbb{Z}_{\ge 0}\) ошибок, если он исправляет ошибки кратности \(0,1,\ldots, t\).
#+end_definition

Иногда код \(\code{C}\) не может исправить все ошибки кратности \(t+1\), однако он может проверить, что \(t+1\) ошибка действительно произошла, но при этом нельзя точно определить сам вектор ошибок.

#+caption: Определение обнаружения конкретной ошибки
#+name: def:code-correct-fix-detect
#+begin_definition
Говорят, что код \(\code{C}\) обнаруживает ошибку \(\boldsymbol{e}\neq \boldsymbol{0}\), если для любого кодового слова \(\boldsymbol{c}\in\code{C}\) вектор \(\boldsymbol{c}+\boldsymbol{e}\) не лежит в коде \(\code{C}\).
#+end_definition

#+caption: Определение обнаружения ошибок фиксированной кратности
#+name: def:code-correct-t-detect
#+begin_definition
Говорят, что код \(\code{C}\) обнаруживает ошибки кратности \(t\in\mathbb{Z}_{>0}\), если он обнаруживает все ошибки \(\boldsymbol{e}\) веса Хемминга \(t\).
#+end_definition

#+caption: Определение обнаружения не более t ошибок
#+name: def:code-correct-detect
#+begin_definition
Говорят, что код \(\code{C}\) обнаруживает \(t\in\mathbb{Z}_{>0}\) ошибок, если он обнаруживает ошибки кратности \(1,2,\ldots, t\).
#+end_definition

Следующая теорема объясняет фундаментальность кодового расстояния.

#+caption: Связь исправляемости и минимального расстояния
#+name: 1.PRO5
#+begin_proposition
Код \(\code{C}\) может исправлять \(t\) ошибок, если и только если его кодовое расстояние \(d_{\code{C}}\) не меньше, чем \(2t+1\), т.е.
\[
d_{\code{C}}\ge 2t+1.
\]
Значит, код с минимальным расстоянием \(d\) может исправлять \(\lfloor(d-1)/2\rfloor\) ошибок.
Если \(d\) чётное, то код может одновременно исправлять \((d-2)/2\) ошибок и обнаруживать \(d/2\) ошибок.
#+end_proposition

** Эквивалентность кодов и группа автоморфизмов
#+name: sec:code-equivalence

#+caption: Определение эквивалентности линейных кодов
#+name: def:code-equivalence
#+begin_definition
Два линейных кода \(\code{C}\) и \(\code{B}\) называются эквивалентными (перестановочно эквивалентными),
если они отличаются только перестановкой координат кодовых слов.
#+end_definition

Например, следующие \([4,2]\)-коды эквивалентны

| \(\code{C}\) | \(\code{B}\) |
| 0000 | 0000 |
| 0011 | 0101 |
| 1100 | 1010 |
| 1111 | 1111 |

так как один из другого получается перестановкой второй и третьей координаты.

Легко видеть, что эквивалентные коды имеют одинаковую длину, одинаковую размерность и одинаковое кодовое расстояние.

Заметим, что для линейных кодов над полями \(\mathbb{F}_q\), \(q\neq 2\), существует более общее определение эквивалентности.
Об этом подробнее можно посмотреть в\nbsp{}[cite:@macwilliams1979].
Однако мы в работе ограничиваемся только введённым понятием перестановочной эквивалентности, как наиболее важном в практических приложениях.

#+caption: Критерий эквивалентности кодов через порождающие матрицы
#+name: prop:when-codes-is-equiv
#+begin_proposition
Пусть \(\code{C}_1\) и \(\code{C}_2\)\nbsp{}--- \([n,k]_q\)-коды.
И пусть \(\matr{G}_1\) и \(\matr{G}_2\) соответственно их некоторые порождающие матрицы.
Коды \(\code{C}\) и \(\code{B}\) эквиваленты, если и только если существует подстановка \(\pi\in S_n\) и невырожденная матрица \(\boldsymbol{M}\) такие, что \(\matr{G}_1\pi=\boldsymbol{M}\cdot\matr{G}_2\).
#+end_proposition

Дадим следующее фундаментальное определение.

#+caption: Определение группы автоморфизмов кода
#+name: def:code-automorphism
#+begin_definition
Множество подстановок координат кодовых слов, отображающих \([n]_q\)-код \(\code{C}\) «на себя», т.\nbsp{}е. переводящих кодовое слово в кодовое слово того же кода, возможно, отличное от исходного, называется группой автоморфизмов кода \(\code{C}\) и обозначается \(\operatorname{Aut}(\code{C})\), т.\nbsp{}е.
\[
\operatorname{Aut}(\code{C})=\{\pi\in S_n\mid\ \code{C}^{\pi}=\code{C}\}.
\]
#+end_definition

Группа \(\operatorname{Aut}(\code{C})\) для \([n]_q\)-кода \(\code{C}\) является подгруппой симметрической группы \(S_n\).

#+caption: Автоморфизмы кода и его дуала
#+name: prop:automorphism-of-dual
#+begin_proposition
Группа автоморфизмов линейного блокового кода \(\code{C}\) совпадает с группой автоморфизмов дуального к нему кода \(\code{C}^{\perp}\), то есть \(\operatorname{Aut}(\code{C})=\operatorname{Aut}(\code{C}^{\perp})\).
#+end_proposition

#+caption: Матричный критерий принадлежности автоморфизму
#+name: prop:authomorphism-matrix
#+begin_proposition
Подстановка \(\pi\) принадлежит группе автоморфизмов \([n,k]_q\)-кода \(\code{C}\) с порождающей матрицей \(\matr{G}\), если и только если \(\boldsymbol{M}\cdot \matr{G}=\matr{G}\cdot\sigma\) для некоторой обратимой \((k\times k)\)-матрицы \(\boldsymbol{M}\).
#+end_proposition

#+caption: Определение полной линейной группы
#+name: def:general-linear-group
#+begin_definition
Множество всех обратимых \((k\times k)\)-матриц над полем \(\mathbb F\) называется полной линейной группой и обозначается через \(GL(k,\mathbb F)\).
Если \(\mathbb F\)\nbsp{}--- конечное поле \(\mathbb{F}_q\), то в этом случае будем использовать обозначение
\(GL(k,q)\).
#+end_definition

#+caption: Порядок полной линейной группы
#+name: prop:order-of-general-linear-group
#+begin_proposition
Порядок полной линейной группы \(GL(k,q)\) равен
\[
(q^k-1)(q^k-q)(q^k-q^2) \ldots (q^k-q^{k-1}).
\]

Согласно утверждению\nbsp{}\ref{prop:authomorphism-matrix} группа автоморфизмов линейного кода размерности \(k\) изоморфна некоторой подгруппе группы \(GL(k,q)\).
#+end_proposition

Утверждение\nbsp{}\ref{prop:authomorphism-matrix} позволяет дать следующее определение.

#+caption: Определение матричного автоморфизма кода
#+name: def:matrix-authomorphism
#+begin_definition
Будем говорить, что невырожденная матрица \(\boldsymbol{M}\) задаёт автоморфизм \(\sigma\) кода \(\code{C}\) с порождающей матрицей \(\matr{G}\), если выполнено равенство \(\boldsymbol{M}\cdot \matr{G}=\matr{G}\cdot\sigma\).
Множество всех матриц, задающих автоморфизмы кода \(\code{C}\), будем обозначать через \(\mathcal A(\code{C})\).
#+end_definition

Почти всегда между матрицами задающими автоморфизм кода и группой автоморфизмов существует взаимно однозначное соответствие.

#+caption: Взаимно однозначное соответствие матриц и автоморфизмов
#+name: prop:one-to-one-matrix-authomorphism
#+begin_proposition
Пусть кодовое расстояние кода \(\code{C}^{\perp}\), дуального к коду \(\code{C}\), строго больше двух.
Тогда любая матрица \(\boldsymbol{A}\in GL(k,q)\), принадлежащая множеству \(\mathcal A(\code{C})\), задаёт единственный автоморфизм \(\gamma\in \operatorname{Aut}(\code{C})\).
И для любой подстановки \(\gamma\in \operatorname{Aut}(\code{C})\) существует единственная матрица \(\boldsymbol{A}\in\mathcal A(\code{C})\), задающая этот автоморфизм.
#+end_proposition

#+begin_proof
Пусть \(\boldsymbol{A}\) принадлежит \(\mathcal A(\code{C})\), тогда найдётся
подстановка \(\gamma\) такая, что
\[
\boldsymbol{A}\matr{G}=\matr{G}\gamma.
\]
Очевидно, что \(\gamma\in \operatorname{Aut}(\code{C})\).
Докажем, что такая \(\gamma\) единственна.
Пусть существуют две подстановки \(\gamma'\) и \(\gamma''\) такие, что
\[
\boldsymbol{A}\matr{G}=\matr{G}\gamma'\;\;\;\boldsymbol{A}\matr{G}=\matr{G}\gamma''.
\]
Тогда
#+caption: Равенство для композиции подстановок
#+name: eq:one-to-one-1
\[
\matr{G}\gamma'\gamma''^{-1}=\matr{G}.
\]
В силу того, что кодовое расстояние \(\code{C}^{\perp}\) строго
больше двух, то в матрице \(\matr{G}\) нет двух одинаковых столбцов, поэтому из равенства\nbsp{}\ref{eq:one-to-one-1} следует, что \(\gamma'\gamma''^{-1}\)\nbsp{}--- тождественная подстановка, поэтому \(\gamma'=\gamma''\).

Докажем, что для \(\gamma\in \operatorname{Aut}(\code{C})\) найдётся единственная
невырожденная матрица \(\boldsymbol{A}\in \mathcal A(\code{C})\).
В силу того, что \(\gamma\in \operatorname{Aut}(\code{C})\), то существует невырожденная матрица \(\boldsymbol{A}\), с которой
\[
\boldsymbol{A}\matr{G}=\matr{G}\gamma.
\]
Понятно, что \(\boldsymbol{A}\in\mathcal A(\code{C})\).
Если найдутся две матрицы \(\boldsymbol{A}'\) и \(\boldsymbol{A}''\) такие, что
\[
\boldsymbol{A}'\matr{G}=\matr{G}\gamma\;\;\boldsymbol{A}''\matr{G}=\matr{G}\gamma,
\]
то будет верно равенство \(\boldsymbol{A}'\matr{G}=\boldsymbol{A}''\matr{G}\).
Ранг матрицы \(\matr{G}\) равен \(k\), поэтому \(\boldsymbol{A}'=\boldsymbol{A}''\).
#+end_proof

** Двоичные коды Рида--Маллера
Настоящий параграф посвящен изложению основных известных фактов о двоичных кодах Рида--Маллера.

Пусть \(f(x_1,\ldots, x_m):V_m\rightarrow V_{1}\)\nbsp{}--- булева функция от \(m\) переменных.
Известно, что любая булева функция может быть представлена в виде алгебраической нормальной формы или полинома Жегалкина, т.е.
#+caption: Алгебраическая нормальная форма булевой функции
#+name: eq:ANF
\begin{equation}
f(x_1,\ldots,x_m)=a_0\oplus\bigoplus_{s=1}^{m}\bigoplus_{1\leqslant
i_1<\ldots<i_s\leqslant m}a_{i_1,\ldots,i_s}x_{i_1}\ldots
x_{i_s}
\end{equation}
для некоторых \(a_0\in V_1\) и \(a_{i_1,\ldots,i_s}\in V_1\), \(1\le s\le m\), \(1\leqslant i_1<\ldots<i_s\leqslant m\).
При этом представление\nbsp{}\ref{eq:ANF} единственное.

Определим степень \(\deg f(x_1,\ldots, x_m)\) булевой функции \(f(x_1,\ldots, x_m)\).
Если среди чисел \(1,2,\ldots, m\) существует наименьшее число \(t\), что для всех \(s\), \(t\le s\le m\), и для всех \(1\le i_1<i_2<\ldots < i_s\le m\) коэффициенты \(a_{i_1,\ldots,i_s}\) в разложении\nbsp{}\ref{eq:ANF} булевой функции \(f(x_1,\ldots, x_m)\) равны \(0\), тогда \(\deg f(x_1,\ldots, x_m)=t-1\).
В противном случае \(\deg f(x_1,\ldots, x_m)=m\).
Таким образом, степень функции \(f(x_1,\ldots, x_m)\) равна максимальной степени мономов, входящих в её полином Жегалкина.

#+caption: Определение кода Рида--Маллера
#+begin_definition
Кодом Рида--Маллера \(\mathcal{RM}(r,m)\), называется множество
вектор-значений \(\boldsymbol{f}\) всех булевых функций
\(f(x_1,\ldots,x_m)\), степень которых не
превосходит \(r\).
#+end_definition

В дальнейшем не будем делать различий в обозначении булевых функций и их векторов значений.
Иногда коды Рида--Маллера называют РМ-кодами (см., например\nbsp{}[cite:@macwilliams1979]).

Очевидно, что длина РМ-кода \(\mathcal{RM}(r,m)\) равна \(n=2^m\).
Далее, РМ-код порядка \(r\) состоит из всех линейных комбинаций векторов, соответствующих произведениям \(1\), \(x_1\), \(\ldots\), \(x_m\), \(x_1x_2\), \(x_1x_3\), \(\ldots\), \(x_mx_{m-1}\), \(\ldots\) (вплоть до степени \(r\)), которые, таким образом, задают базис кода.
Всего имеется
\begin{equation}
k=1+\binom{m}{1}+\binom{m}{2}+\ldots+\binom{m}{r}
\end{equation}
таких базисных векторов.
Все они линейно независимы.
Следовательно, размерность кода равна \(k\).

Через \(\boldsymbol{R}\) будем обозначать порождающую матрицу
кода Рида--Маллера \(\mathcal{RM}(r,m)\) следующего вида
\[
\boldsymbol{R}=\begin{pmatrix}
\matr{G}_0 \\
\matr{G}_1 \\
\vdots     \\
\matr{G}_r
\end{pmatrix},
\]
где
\[\matr{G}_0=(1,1\ldots,1),\]
\[
\matr{G}_1=\begin{pmatrix}
\boldsymbol{x_m} \\
\vdots     \\
\boldsymbol{x_2} \\
\boldsymbol{x_1}
\end{pmatrix},
G_2=\begin{pmatrix}
\boldsymbol{x_{m-1}x_m} \\
\vdots            \\
\boldsymbol{x_1x_3}     \\
\boldsymbol{x_1x_2}
\end{pmatrix},
\matr{G}_r=\begin{pmatrix}
\boldsymbol{x_{m-r+1}x_{m-r+2}\ldots x_m} \\
\vdots                              \\
\boldsymbol{x_1x_2\ldots x_{r-1}x_{r+1}}  \\
\boldsymbol{x_1x_2\ldots x_{r-1}x_r}
\end{pmatrix},
\]
здесь \(\boldsymbol{f}\)\nbsp{}--- вектор значений булевой функции \(f(x_1,\ldots,x_m)\).
Матрицу \(\boldsymbol{R}\) такого вида будем называть стандартной порождающей матрицей кода Рида--Маллера \(\mathcal{RM}(r,m)\).

РМ-коды длины \(2^{m+1}\) могут быть получены из РМ-кодов длины \(2^m\) с помощью конкатенации вида \((\boldsymbol{f}\|\boldsymbol{f}\oplus \boldsymbol{g})\), которая иногда называется конструкцией Плоткина\nbsp{}[cite:@macwilliams1979].

#+caption: Конструкция Плоткина для кодов Рида--Маллера
#+name: prop:rm-plotkin-construction
#+begin_proposition
Пусть \(\matr{G}(r,m)\)\nbsp{}--- порождающая матрица кода \(\mathcal{RM}(r,m)\).
Тогда, во-первых,
\[
\mathcal{RM}(r+1,m+1)=\{(\boldsymbol{f}\|\boldsymbol{f}\oplus \boldsymbol{g}):\;\boldsymbol{f}\in \mathcal{RM}(r+1,m),\;\boldsymbol{g}\in \mathcal{RM}(r,m)\},
\]
а во-вторых
\[
\matr{G}(r+1,m+1)=\begin{pmatrix}
\matr{G}(r+1,m)&\matr{G}(r+1,m)\\
\boldsymbol{0}&\matr{G}(r,m)
\end{pmatrix}.
\]
#+end_proposition

Приведём ряд фактов, описывающих свойства кодов Рида--Маллера.

#+caption: Минимальное расстояние кода Рида--Маллера
#+name: prop:rm-code-distance
#+begin_proposition
Кодовое расстояние кода \(\mathcal{RM}(r,m)\) равно \(2^{m-r}\).
#+end_proposition

#+caption: Вложенность кодов Рида--Маллера по порядку
#+name: prop:rm-code-inclosure
#+begin_proposition
Для всех \(0\le r<t\le m-1\) выполнено включение \(\mathcal{RM}(r,m)\subset \mathcal{RM}(t,m)\).
#+end_proposition

#+caption: Дуальность кодов Рида--Маллера
#+name: prop:rm-dual-code
#+begin_proposition
Для всех \(0\le r\le m-1\) код \(\mathcal{RM}(m-r-1,m)\) дуален коду \(\mathcal{RM}(r,m)\), т.\nbsp{}е.
\begin{equation}
\mathcal{RM}^{\perp}(r,m)=\mathcal{RM}(m-r-1,m).
\end{equation}
#+end_proposition

Тем самым код, дуальный к РМ-коду сам является РМ-кодом.

Рассмотрим класс кодов, которые получаются из кодов Рида--Маллера операцией укорочения.
Речь идёт о выколотых кодах Рида--Маллера.

#+caption: Определение выколотого кода Рида--Маллера
#+name: def:rm-shorted
#+begin_definition
Для любого \(r\), \(0\le r\le m-1\) выколотым кодом Рида--Маллера \(\mathcal{RM}^{\star}(r,m)\) называется код, который получается из кода \(\mathcal{RM}(r,m)\) выкалыванием (или вычёркиванием) из всех кодовых слов координаты, соответствующей нулевой \(m\)-последовательности
\[
x_1=\ldots=x_m=0.
\]
#+end_definition

На самом деле не существенно какую координату выколоть\nbsp{}--- во всех случаях получаются эквивалентные коды (см., например,\nbsp{}[cite:@macwilliams1979]).

#+caption: Параметры выколотого кода Рида--Маллера
#+name: prop:rm-shorted-parameters
#+begin_proposition
Код \(\mathcal{RM}^*(r,m)\) имеет длину \(n=2^{m}-1\), кодовое расстояние \(d=2^{m-r}-1\) и размерность \(k=1+\binom{m}{1}+\binom{m}{2}+\ldots+\binom{m}{r}\).
#+end_proposition

Рассмотрим вопрос о количестве векторов минимального веса кода Рида--Маллера, а также изучим общий вид этих векторов.

#+caption: Вид слов минимального веса в коде Рида--Маллера
#+name: prop:rm-code-minimal-weight-code-words
#+begin_proposition
Вектор \(\boldsymbol{f}\) является словом минимального веса в коде \(\mathcal{RM}(r,m)\), если и только если найдётся система из \(r\) линейно независимых векторов-значений \(\boldsymbol{l}_i\) линейных функций \(l_i(x_1,\ldots, x_m)\), что
\begin{equation}
\boldsymbol{f}=\boldsymbol{l}_1\cdot \boldsymbol{l}_2\cdots\boldsymbol{l}_r.
\end{equation}
#+end_proposition

#+caption: Число слов минимального веса в кодах Рида--Маллера
#+name: prop:rm-number-of-minimal-weight-words
#+begin_proposition
Число слов минимального веса
- *a):* в коде \(\mathcal{RM}^{\star}(r,m)\) равно
  \begin{equation}
  A_{2^{m-r}-1}=\prod_{i=0}^{m-r-1}\frac{2^{m-i}-1}{2^{m-r-i}-1};
  \end{equation}
- *b):* в коде \(\mathcal{RM}(r,m)\) равно
  \begin{equation}
  A_{2^{m-r}}=2^r\prod_{i=0}^{m-r-1}\frac{2^{m-i}-1}{2^{m-r-i}-1};
  \end{equation}
#+end_proposition

#+caption: Базис из слов минимального веса
#+name: prop:min-weight-code-words-generate-rm
#+begin_proposition
В кодах \(\mathcal{RM}(r,m)\) и \(\mathcal{RM}^{\star}(r,m)\) имеется базис, состоящий из слов минимального веса.
#+end_proposition

#+caption: Определение полной аффинной группы
#+name: def:general-affine-group
#+begin_definition
Пусть \(\boldsymbol{A}=(a_{ij})\)\nbsp{}--- двоичная обратимая матрица размера \((m\times m)\), и пусть \(\boldsymbol{b}\)\nbsp{}--- \(m\)-вектор над полем \(\mathbb{F}_q\).
Преобразование
\[ T:\;\text{заменить } \begin{pmatrix}
x_1\\
x_2\\
\vdots\\
x_m
\end{pmatrix}
\; \text{на }
\boldsymbol{A}\begin{pmatrix}
x_1\\
x_2\\
\vdots\\
x_m
\end{pmatrix}
\oplus \boldsymbol{b} \]
представляет собой подстановку на множестве из \(2^m\) двоичных векторов длины \(m\), переводящую \(\boldsymbol{0}\) в \(\boldsymbol{b}\).
Множество все таких подстановок называется полной аффинной группой и обозначается \(GA(m,q)\).
#+end_definition

Заметим, что множество подгруппа группы \(GA(m,q)\), содержащая преобразования \(T\), в которых \(\boldsymbol{b}=\boldsymbol{0}\) изоморфна полной линейной группе \(GL(m,q)\).

Действие преобразования \(T\in GA(m,2)\) на множестве булевых функций описывается следующим образом:
\begin{equation}
T:\;f(x_1,x_2,\ldots,x_m)\mapsto f\left(\sum a_{1j}x_j\oplus b_1,\sum a_{2j}x_j\oplus b_2,\ldots,\sum a_{mj}x_j\oplus b_m\right).
\end{equation}

Ясно, что это преобразование не увеличивает степень булевой функции, поэтому верно включение
\begin{equation}
Aut(\mathcal{RM}(r,m))\subset GA(m,2).
\end{equation}

Оказывается верным и обратное включение.
Справедливо следующее утверждение\nbsp{}\ref{prop:rm-authomorphism-group}.

#+caption: Группа автоморфизмов кодов Рида--Маллера
#+name: prop:rm-authomorphism-group
#+begin_proposition
((\cite{McWilliams_1979})).
- *1):* Для \(r=0\) или \(r=m-1\) группа автоморфизмов кода \(\mathcal{RM}^{\star}(r,m)\) совпадает с группой \(S_{2^m-1}\), т.\nbsp{}е.
  \begin{equation}
  \operatorname{Aut}(\mathcal{RM}^{\star}(r,m))=S_{2^m-1};
  \end{equation}
- *2):* для \(r=0\), \(r=m-1\) или \(r=m\) группа автоморфизмов кода \(\mathcal{RM}(r,m)\) совпадает с группой \(S_{2^m}\), т.\nbsp{}е.
  \begin{equation}
  \operatorname{Aut}(\mathcal{RM}(r,m))=S_{2^m};
  \end{equation}
- *3):* для \(1\le r\le m-2\) группа автоморфизмов кода \(\mathcal{RM}^{\star}(r,m)\) совпадает с группой \(GL(m,2)\), т.\nbsp{}е.
  \begin{equation}
  \operatorname{Aut}(\mathcal{RM}^{\star}(r,m))=GL(m,2);
  \end{equation}
- *4):* для \(1\le r\le m-2\) группа автоморфизмов кода \(\mathcal{RM}(r,m)\) совпадает с группой \(GA(m)\), т.\nbsp{}е.
  \begin{equation}
  \operatorname{Aut}(\mathcal{RM}(r,m))=GA(m).
  \end{equation}
#+end_proposition

Завершим обзор РМ-кодов весьма важной теоремой Мак-Элиса, доказательство которой можно найти в\nbsp{}\cite{McWilliams_1979}.

#+caption: Делимость весов слов в коде Рида--Маллера
#+name: prop:mceliece-thm
#+begin_proposition
Р.Дж.Мак-Элис\nbsp{}\cite{McWilliams_1979}.
Вес каждого слова в коде \(\mathcal{RM}(r,m)\) кратен \(2^{\lceil\frac{m-1}{r}\rceil}\).
#+end_proposition

** Квадратичные формы над конечными полями

#+caption: Определение квадратичной формы над конечным полем
#+name: def:quad-form
#+begin_definition
Квадратичной формой над полем \(\mathbb{F}_q\) называется однородный квадратичный многочлен над этим полем:
\[ q(x_1,\dots,x_m) =
\sum_{1 \le i < j \le m} a_{i, j} x_i x_j +
\sum_{i = 1}^m b_i x_i^2,
\]
где \(a_{i, j} \in \mathbb{F}_q, 1 \le i < j \le m\) , и \(b_i \in \mathbb{F}_q, 1\le i\le m\).
Обозначим через \(\mathcal{Q}_m(q)\) множество всех квадратичных форм над полем \(\mathbb{F}_q\) от \(m\) переменных.
#+end_definition

Заметим, что в полях характеристики \(2\), т.е. в полях вида \(GF(2^s)\),
квадратичная форма принимает вид неоднородного многочлена, так как \(x^2=x\):
\[ q(x_1,\dots,x_m) =
\sum_{1 \le i < j \le m} a_{i, j} x_i x_j +
\sum_{i = 1}^m b_i x_i.
\]

Легко проверить, что множество квадратичных форм от \(m\) переменных образует линейное подпространство пространства \(V_{q^m}(q)\).
Поэтому \(Q_m(q)\) является \([q^m]_q\)-кодом \(\mathcal{HRM}_q(2,m)\).
Причём \(\mathcal{HRM}_q(2,m)\) является подкодом кода Рида--Маллера \(\mathcal{RM}_q(2,m)\).

В приложениях важной характеристикой кода \(\mathcal{HRM}_q(2,m)\) является его спектр весов \(\boldsymbol{A}(\mathcal{HRM}_q(2,m))\)(см.\nbsp{}\ref{def:weight-spectrum}).

Спектры весов недвоичного кода Рида--Маллера и соответственно спектр кода \(\mathcal{HRM}_q(2,m)\) для \(q>2\) был получен впервые Р.\nbsp{}Мак-Элисом
в работе\nbsp{}\cite{mcelieceQuadraticFormsFinite1969}.
А спектры весов двоичного кода Рида--Маллера и двоичных квадратичных форм был вычислен Н.\nbsp{}Слоеном и Е.\nbsp{}Берлекемпом в
работе\nbsp{}\cite{n.sloaneWeightEnumeratorSecondorder1970}.
В силу того, что позднее в фундаментальных статьях\nbsp{}\cite{mcelieceQuadraticFormsFinite1969,n.sloaneWeightEnumeratorSecondorder1970}
были найдены ошибки, в настоящей работе спектры весов кода \(\mathcal{HRM}_q(2,m)\) приводится с соответствии со статьёй Ш.\nbsp{}Ли\nbsp{}\cite{shuxingliWeightDistributionSecond2019}.

#+caption: Спектр весов кода квадратичных форм
#+name: prop:weight-spectrum-quad-form
#+begin_proposition
Спектр весов \(\boldsymbol{A}(\mathcal{HRM}_q(2,m))\) имеет следующий вид
1. \(A_0=1\);
2. \(A_{q^m-q^{m-1}-\tau q^{m-1-j}(q-1)}=\frac{q^{j^2}(q^j+\tau)}{2}\frac{\prod_{i=m-2j+1}^m(q^i-1)}{\prod_{i=1}^j(q^{2i}-1)}\), \(j=1,2,\ldots,\lfloor m/2\rfloor\) и \(\tau=-1,1\);
3. \(A_{q^m-q^{m-1}}=q^{m}-1+\sum_{j=1}^{\lfloor (m-1)/2\rfloor}q^{j(j+1)}\frac{\prod_{i=m-2j}^m(q^i-1)}{\prod_{i=1}^j(q^{2i}-1)}\);
4. \(A_w=0\) для всех остальных значений \(w \neq 0, q^{m}-q^{m-1}\), а также \(w\neq q^m-q^{m-1}-\tau q^{m-1-j}(q-1)\) для всех \(j=1,2,\ldots,\lfloor m/2\rfloor\), \(\tau=-1,1\).
#+end_proposition


* Произведение Шура--Адамара некоторых классов линейных кодов :noexport:
** Произведение Адамара линейных кодов

#+caption: Определение произведения Адамара векторов
#+begin_definition
Пусть \(\boldsymbol{c}=(c_1,\ldots, c_n)\) и \(\boldsymbol{b}=(b_1,\ldots, b_n)\)\nbsp{}--- векторы длины \(n\) над полем \(\mathbb{F}_q\).
Тогда произведением Адамара (произведением Шура, покомпонентным произведением) векторов \(\boldsymbol{c}\) и \(\boldsymbol{b}\) называется вектор
\[
\boldsymbol{c}\cdot \boldsymbol{b}=(c_1\cdot b_1,\ldots, c_n\cdot b_n).
\]
#+end_definition

Легко проверить линейность произведения Адамара векторов, как по первому, так и по второму аргументу.

#+caption: Определение произведения Адамара 1 кодов
#+name: def:hadamard-product-whole
#+begin_definition
Пусть \(\code{C}\) и \(\code{B}\)\nbsp{}--- два \([n]_q\)-кода.
Тогда произведением Адамара 1 кодов \(\code{C}\) и \(\code{B}\) называется код \(\code{C}\operatorname{\circ}_1 \code{B}\), который совпадает с линейной оболочкой множества
\[
\{\boldsymbol{c}\cdot \boldsymbol{b}\mid\ \boldsymbol{c}\in \code{C},\ \boldsymbol{b}\in \code{B}\}.
\]
#+end_definition

#+caption: Определение произведения Адамара 2 кодов через базисы
#+name: def:hadamard-product-basis
#+begin_definition
Пусть \(\code{C}\)\nbsp{}--- \([n,k_{\code{C}}]_{q}\)-код с базисом \(\{\boldsymbol{c}_1,\ldots, \boldsymbol{c}_{k_{\code{C}}}\}\), \(\code{B}\)\nbsp{}--- \([n,k_{\code{B}}]_{q}\)-код с базисом \(\{\boldsymbol{b}_1,\ldots, \boldsymbol{b}_{k_{\code{B}}}\}\).
Тогда произведением Адамара 2 кодов \(\code{C}\) и \(\code{B}\) называется код \(\code{C}\operatorname{\circ}_2 \code{B}\), который совпадает с линейной оболочкой множества
\[
\{\boldsymbol{c}_i\operatorname{\circ} \boldsymbol{b}_j,\ i=1,\ldots, k_{\code{C}},\ j=1,\ldots, k_{\code{B}}\}.
\]
#+end_definition

#+caption: Эквивалентность двух определений произведения Адамара кодов
#+begin_proposition
Произведения Адамара 1 и 2 кодов \(\code{C}\) и \(\code{B}\) совпадают.
#+end_proposition

#+begin_proof
Докажем, что \(\code{C}\operatorname{\circ}_1 \code{B}\subseteq \code{C}\operatorname{\circ}_2 \code{B}\).
Пусть \(\boldsymbol{c}\) и \(\boldsymbol{b}\) два произвольных слова кодов \(\code{C}\) и \(\code{B}\) соответственно.
Тогда существуют такие наборы элементов \(\alpha_1,\ldots,\alpha_{k_{\code{C}}} \in \mathbb{F}_q\) и \(\beta_1,\ldots,\beta_{k_{\code{B}}}\in \mathbb{F}_q\), что
\[
\boldsymbol{c}=\alpha_1\boldsymbol{c}_1+\ldots+\alpha_{k_{\code{C}}}\boldsymbol{c}_{k_{\code{C}}},\ \boldsymbol{b}=\beta_1\boldsymbol{b}_1+\ldots+\beta_{k_{\code{B}}}\boldsymbol{b}_{k_{\code{B}}}.
\]
В силу линейности произведения Адамара векторов получим, что
\[
\boldsymbol{c}\cdot \boldsymbol{b} = \sum_{i=1}^{k_{\code{C}}}\sum_{j=1}^{k_{\code{B}}}\alpha_i\beta_j(\boldsymbol{c}_i\cdot \boldsymbol{b}_j),
\]
т.е. \(\boldsymbol{c}\cdot \boldsymbol{b}\) раскладывается в линейную комбинацию векторов из кода \(\code{C}\operatorname{\circ}_2 \code{B}\), что доказывает включение.

Справедливость обратного включения \(\code{C}\operatorname{\circ}_2 \code{B}\subseteq \code{C}\operatorname{\circ}_1 \code{B}\) следует из очевидного включения множеств
\[
\{\boldsymbol{c}_i\cdot \boldsymbol{b}_j,\ i=1,\ldots, k_{\code{C}},\ j=1,\ldots, k_{\code{B}}\}\subseteq \{\boldsymbol{c}\cdot \boldsymbol{b}\mid\ \boldsymbol{c}\in \code{C},\ \boldsymbol{b}\in \code{B}\}.
\]
#+end_proof

Таким образом, оба определения произведения Адамара кодов эквивалентны, и можно считать, что они определяют одну операцию произведение Адамара \(\code{C}\operatorname{\circ} \code{B}\), т.е. \(\code{C}\operatorname{\circ}_1 \code{B}=\code{C}\operatorname{\circ}_2\code{B}=\code{C}\operatorname{\circ} \code{B}\).

#+caption: Определение суммы линейных кодов
#+name: def:sum-codes
#+begin_definition
Суммой \([n]_q\)-кодов \(\code{A}\) и \(\code{B}\) называется \([n]_q\)-код \(\code{A}+\code{B}\), состоящий из векторов \(\boldsymbol{a}+\boldsymbol{b}\) для всех \(\boldsymbol{a}\in\code{A}\) и \(\boldsymbol{b}\in \code{B}\).
#+end_definition

Следующее утверждение содержит базовые свойства произведения Адамара линейных кодов.

#+caption: Базовые свойства произведения Адамара кодов
#+name: prop:hadamard-prod-properties
#+begin_proposition
Для любых \([n]_q\)-кодов \(\code{A}, \code{B}\) и \(\code{C}\) выполнены равенства
1. \((\code{A}\operatorname{\circ}\code{B})\operatorname{\circ} \code{C}=\code{A}\operatorname{\circ} (\code{B}\operatorname{\circ} \code{C})\);
2. \(\code{B}\operatorname{\circ} \code{C}=\code{C}\operatorname{\circ} \code{B}\);
3. \((\code{A}+\code{B})\operatorname{\circ} \code{C}=\code{A}\operatorname{\circ} \code{C}+ \code{B}\operatorname{\circ} \code{C}\);
4. \(\mathcal{O}_n\operatorname{\circ} \code{C}=\code{C}\operatorname{\circ} \mathcal{O}_n=\mathcal{O}_n\), здесь \(\mathcal{O}_n\)\nbsp{}--- \([n]_q\)-код, состоящий из нулевого вектора длины \(n\);
5. \(\mathcal{R}_n\operatorname{\circ} \code{C}=\code{C}\operatorname{\circ} \mathcal{R}_n=\code{C}\), здесь \(\mathcal{R}_n\)\nbsp{}--- \([n]_q\)-код, состоящий из нулевого вектора и вектора из всех единиц длины \(n\) (такой код называется кодом с повторением длины \(n\)).
#+end_proposition

Таким образом, множество \([n]_q\)-кодов относительно произведения Адамара является квазигруппой с единицей, т.\nbsp{}е. моноидом.

Кроме того, множество \([n]_q\)-кодов относительно операции сложения кодов и произведения Адамара является коммутативным полукольцом с единицей \(\mathcal{R}_n\).

#+caption: Определение квадрата Адамара кода
#+name: def:hadamard-square
#+begin_definition
Произведение Адамара кода \(\code{C}\) на себя называется квадратом Адамара кода \(\code{C}\) или просто квадратом кода \(\code{C}\), квадрат Адамара будем обозначать символом \(\code{C}^{\operatorname{\circ} 2}\).
Таким образом,
\[
\code{C}^{\operatorname{\circ} 2} = \code{C}\operatorname{\circ}\code{C}.
\]
#+end_definition

Определение\nbsp{}\ref{def:hadamard-square} можно обобщить на случай произвольного числа произведений Адамара кода \(\code{C}\) на себя.

#+caption: Определение s той степени Адамара кода
#+name: def:hadamard-deg
#+begin_definition
Для произвольного натурального \(s\) код
\[
\code{C}^{\operatorname{\circ} s}=\underbrace{\code{C}\operatorname{\circ}\code{C}\operatorname{\circ}\ldots\operatorname{\circ}\code{C}}_{s}
\]
называется \(s\)-той степенью Адамара кода \(\code{C}\) или просто \(s\)-той степенью кода \(\code{C}\).
#+end_definition

Из определения\nbsp{}\ref{def:hadamard-product-whole} следуют следующие простые свойства произведения Адамара кодов.

#+caption: Монотонность произведения Адамара по включению
#+name: prop:hadamard-product-subcodes
#+begin_proposition
Пусть \(\code{C}_1\), \(\code{C}_2\), \(\code{B}_1\) и \(\mathcal{B_1}\) такие \([n]_q\)-коды, что \(\code{C}_1\subseteq\code{C}_2\) и \(\code{B}_1\subseteq\code{B}_2\).
Тогда верно включение
#+caption: Включение произведений Адамара для вложенных кодов
#+name: def:hadamard-product-subspace
\begin{equation}
\code{C}_1\operatorname{\circ}\code{C}_2\subseteq\code{B}_1\operatorname{\circ}\code{B}_2.
\end{equation}
#+end_proposition

Заметим, что если в условиях утверждения\nbsp{}\ref{prop:hadamard-product-subcodes} включения \(\code{C}_1\subsetneq\code{C}_2\) и \(\code{B}_1\subsetneq\code{B}_2\) строгие, то из этого, вообще говоря, не следует, что включение\nbsp{}\ref{def:hadamard-product-subspace} также является строгим.
Приведём контрпример для случая \(\code{C}_1=\code{C}_2\), \(\code{B}_1=\code{B}_2\).

Пусть \(\code{B}\) порождается матрицей
#+caption: Пример порождающей матрицы кода B
#+name: eq:hadamard-product-subspace-example
\begin{equation}
\begin{pmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 \\
0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 \\
0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 \\
0 & 0 & 0 & 0 & 0 & 0 & 1 & 1 \\
\end{pmatrix},
\end{equation}
а код \(\code{C}\) матрицей
\[
\begin{pmatrix}
1 & 1 & 1 & 1 & 1 & 1 & 1 & 1 \\
0 & 0 & 0 & 0 & 1 & 1 & 1 & 1 \\
0 & 0 & 1 & 1 & 0 & 0 & 1 & 1 \\
\end{pmatrix}.
\]

Тогда коды \(\code{B}^{\operatorname{\circ} 2}\) и \(\code{C}^{\operatorname{\circ} 2}\) совпадают с кодом \(\code{B}\)
и порождаются матрицей\nbsp{}\ref{eq:hadamard-product-subspace-example}.
А при этом выполнено строгое включение \(\code{C}\subset\code{B}\).

#+caption: Алгоритмическая сложность построения базиса произведения Адамара
#+name: thm:hadamard-product-alg-complexity
#+begin_theorem
Cуществует алгоритм, который по базису \([n,k_1\ge 1]_q\)-кода \(\code{C}\) и базису \([n,k_2\ge 1]_q\)-кода \(\code{B}\)
строит базис кода \(\code{C}\operatorname{\circ}\code{B}\) и имеет сложность не более \(8n\cdot k\cdot k_{1}\cdot k_{2}\).
операций в поле \(\mathbb{F}_q\), здесь \(k=\dim\code{C}\operatorname{\circ}\code{B}\).
#+end_theorem

#+begin_proof
Рассмотрим базис \(\{\boldsymbol{c}_{1},\ldots,\boldsymbol{c}_{k_{1}}\}\) кода \(\code{C}\) и
базис \(\{\boldsymbol{b}_{1},\ldots,\boldsymbol{b}_{k_{2}}\}\) кода \(\code{B}\).
Построим базис \(L=\{\boldsymbol{\ell}_1,\ldots,\boldsymbol{\ell}_k\}\), \(k=\dim\code{C}\operatorname{\circ}\code{B}\), кода \(\code{C}\operatorname{\circ}\code{B}\).

Будем формировать \(L\) следующим образом.
Пусть сначала \(L=\emptyset\).
Будем последовательно перебирать векторы \(\boldsymbol{c}_i\operatorname{\circ}\boldsymbol{b}_j\), \(i=1,\ldots, k_1\), \(j=1,\ldots, k_2\).
Выберем первый вектор \(\boldsymbol{a}=\boldsymbol{c}_{1}\operatorname{\circ}\boldsymbol{b}_{1}\).
Найдём первую ненулевую координату в \(\boldsymbol{a}\).
Если \(\boldsymbol{a}=\boldsymbol{0}\), то переходим к следующему произведению \(\boldsymbol{a}\leftarrow\boldsymbol{c}_1\operatorname{\circ}\boldsymbol{b}_2\),
и продолжаем поиск ненулевой координаты \(\boldsymbol{a}\).
Если перебрав все векторы \(\boldsymbol{c}_i\operatorname{\circ}\boldsymbol{b}_j\), не будет найден ненулевой вектор, то алгоритм
останавливается и выдаёт \(L=\{\boldsymbol{0}\}\), так как в этом случае \(\code{C}\operatorname{\circ}\code{B}=\mathcal{O}\).
Когда будет найден ненулевой вектор \(\boldsymbol{a}\) c первой ненулевой координатой \(i_1\in\{1,2,\ldots, n\}\),
то добавим вектор \(\boldsymbol{\ell}_1=a_{i_1}^{-1}\boldsymbol{a}\) к \(L\), \(L=L\cup\{\boldsymbol{\ell}\}\).
При этом совокупный ранг векторов в \(L\) будет равен \(1\).
Причём в первом (и пока единственном) векторе в координате с номером \(i_1\) будет стоять \(1\).

Пусть для построения \(L\) на этом шаге потребовалось рассмотреть \(n_1\) векторов \(\boldsymbol{a}\).
Тогда для поиска ненулевого \(\boldsymbol{a}\) потребовалось выполнить \(n\cdot n_1\) операций сравнения элементов поля \(\mathbb{F}_q\).
А для вычисления вектора \(\boldsymbol{\ell}_1\) потребовалось не более \(n\) операций деления.
При этом для формирования каждого вектора \(\boldsymbol{a}\) нужно вычислить произведение \(\boldsymbol{c}\operatorname{\circ}\boldsymbol{b}\),
для чего требуется \(n\) операций умножения элементов поля \(\mathbb{F}_q\).
Т.е. для построения всех векторов \(\boldsymbol{a}\) потребуется \(n\cdot n_1\) операций в поле \(\mathbb{F}_q\).
Итого для формирования \(L\) на этом шаге нужно \(2n\cdot n_1+n\) операций в поле \(\mathbb{F}_q\).

Если для построения \(L\) ранга \(1\) были перебраны все \(k_1\cdot k_2\) произведений
\(\boldsymbol{c}_i\operatorname{\circ}\boldsymbol{b}_j\), \(i=1,\ldots, k_1\), \(j=1,\ldots,k_2\),
то \(L\) будет содержать искомый базис кода \(\code{C}\operatorname{\circ}\code{B}\).
Алгоритм останавливается и возвращает \(L\).

Иначе продолжаем строить базис кода \(L\).
Выберем следующее произведение \(\boldsymbol{c}_i\operatorname{\circ} \boldsymbol{b}_j\), которое не встречалось ранее.
Вычислим вектор \(\boldsymbol{a}= \boldsymbol{c}_i\operatorname{\circ} \boldsymbol{b}_j-a_{i_1}\cdot\boldsymbol{\ell}_1\).
Если \(\boldsymbol{a}=\boldsymbol{0}\), то выбираем следующее произведение \(\boldsymbol{c}_i\operatorname{\circ} \boldsymbol{b}_j\)
и опять вычисляем \(\boldsymbol{a}\).

Если все векторы \(\boldsymbol{c}_i\operatorname{\circ} \boldsymbol{b}_j\) исчерпаны, а ненулевой вектор \(\boldsymbol{a}\)
построить не удалось, то алгоритм останавливается и возвращает \(L\).
Иначе пусть \(i_2\)\nbsp{}--- номер первой ненулевой координаты вектора \(\boldsymbol{a}\).
Вычислим \(\boldsymbol{\ell}_2=a_{i_2}^{-1}\boldsymbol{a}\) и добавим его к \(L\), \(L=\{\boldsymbol{\ell}_1,\boldsymbol{\ell}_2\}\).
Заметим, что в итоге система \(L\) имеет ранг \(2\) и приведена к верхнетреугольному виду с точностью
до перестановки координат векторов.

Пусть для построения \(L\) на этом шаге потребовалось рассмотреть \(n_2\) векторов \(\boldsymbol{c}_i\operatorname{\circ} \boldsymbol{b}_j\).
При этом для формирования каждого вектора \(\boldsymbol{a}\) нужно вычислить произведение Адамара векторов,
для чего требуется \(n\) операций умножения элементов поля \(\mathbb{F}_q\).
Далее потребуется не более \(n\) операций умножения и \(n\) операций вычитания элементов поля \(\mathbb{F}_q\).
Для проверки неравенства \(\boldsymbol{a}\neq\boldsymbol{0}\) нужно выполнить \(n\) операций сравнения
элементов поля \(\mathbb{F}_q\).
Таким образом, для поиска ненулевого вектора \(\boldsymbol{a}\) потребуется \(4n\cdot n_2\) операций в поле \(\mathbb{F}_q\).
Далее, для построения элемента \(\boldsymbol{\ell}_2\) нужно выполнить \(n\) операций деления в поле \(\mathbb{F}_q\).
Итого для формирования \(L\) на этом шаге нужно \(4n\cdot n_2+n\) операций в поле \(\mathbb{F}_q\).

Теперь пусть было построено \(L=\{\boldsymbol{\ell}_1,\boldsymbol{\ell}_2,\ldots,\boldsymbol{\ell}_{t-1}\}\) ранга \(L\).

Если для построения \(L\) ранга \(t-1\) были перебраны все \(k_1\cdot k_2\) произведений
\(\boldsymbol{c}_i\operatorname{\circ}\boldsymbol{b}_j\), \(i=1,\ldots, k_1\), \(j=1,\ldots,k_2\),
то \(L\) будет содержать искомый базис кода \(\code{C}\operatorname{\circ}\code{B}\).
Алгоритм останавливается и возвращает \(L\).

Иначе продолжаем строить базис кода \(L\).
Выберем следующее произведение \(\boldsymbol{c}_i\operatorname{\circ} \boldsymbol{b}_j\), которое не встречалось ранее.
Вычислим вектор
\[
\boldsymbol{a}=
\boldsymbol{c}_i\operatorname{\circ} \boldsymbol{b}_j
-a_{i_1}\cdot\boldsymbol{\ell}_1-a_{i_2}\cdot\boldsymbol{\ell}_2-\ldots-a_{i_{t-1}}\cdot\boldsymbol{\ell}_{t-1}.
\]
Если \(\boldsymbol{a}=\boldsymbol{0}\), то выбираем следующее произведение \(\boldsymbol{c}_i\operatorname{\circ} \boldsymbol{b}_j\)
и опять вычисляем \(\boldsymbol{a}\).

Если все векторы \(\boldsymbol{c}_i\operatorname{\circ} \boldsymbol{b}_j\) исчерпаны, а ненулевой вектор \(\boldsymbol{a}\)
построить не удалось, то алгоритм останавливается и возвращает \(L\).
Иначе пусть \(i_t\)\nbsp{}--- номер первой ненулевой координаты вектора \(\boldsymbol{a}\).
Вычислим \(\boldsymbol{\ell}_t=a_{i_t}^{-1}\boldsymbol{a}\) и добавим его к \(L\), \(L=\{\boldsymbol{\ell}_1,\ldots,\boldsymbol{\ell}_t\}\).
Заметим, что в итоге система \(L\) имеет ранг \(t\) и приведена к верхнетреугольному виду с точностью
до перестановки координат векторов.

Пусть для построения \(L\) на этом шаге потребовалось рассмотреть \(n_t\) векторов \(\boldsymbol{c}_i\operatorname{\circ} \boldsymbol{b}_j\).
При этом для формирования каждого вектора \(\boldsymbol{a}\) нужно вычислить произведение Адамара векторов,
для чего требуется \(n\) операций умножения элементов поля \(\mathbb{F}_q\).
Далее потребуется не более \((t-1)n\) операций умножения и \((t-1)n\) операций вычитания элементов поля \(\mathbb{F}_q\).
Для проверки неравенства \(\boldsymbol{a}\neq\boldsymbol{0}\) нужно выполнить \(n\) операций сравнения
элементов поля \(\mathbb{F}_q\).
Таким образом, для поиска ненулевого вектора \(\boldsymbol{a}\) потребуется \(2tn\cdot n_t\) операций в поле \(\mathbb{F}_q\).
Далее, для построения элемента \(\boldsymbol{\ell}_t\) нужно выполнить \(n\) операций деления в поле \(\mathbb{F}_q\).
Итого для формирования \(L\) на этом шаге нужно \(2tn\cdot n_t+n\) операций в поле \(\mathbb{F}_q\).

Процесс построения \(L\) продолжается до тех пор пока все произведения \(\boldsymbol{c}_i\operatorname{\circ}\boldsymbol{b}_j\) не будут исчерпаны.
Описанный алгоритм приведён в псевдокоде в алгоритме\nbsp{}\ref{alg:hadamard-product-basis}.

#+name: alg:hadamard-product-basis
#+begin_algorithm
\caption{Построение базиса кода \(\code{C}\operatorname{\circ}\code{B}\)}
\KwData{
- *1):* \(\{\boldsymbol{c}_1,\dots,\boldsymbol{c}_{k_1}\}\)\nbsp{}--- базис кода \(\code{C}\);
- *2):* \(\{\boldsymbol{b}_1,\dots,\boldsymbol{b}_{k_2}\}\)\nbsp{}--- базис кода \(\code{B}\).
}
\KwResult{
\(L=\{\boldsymbol{\ell}_1,\dots,\boldsymbol{\ell}_{k}\}\)\nbsp{}--- базис кода \(\code{C}\operatorname{\circ}\code{B}\).
}
\(L\leftarrow\emptyset\);
\(I\leftarrow\emptyset\);
\(t\leftarrow 0\)\;
\For{\(i\gets 1\) \KwTo \(k_1\)}{
\For{\(j\gets 1\) \KwTo \(k_2\)}{
\(\boldsymbol{a}\leftarrow \boldsymbol{c}\operatorname{\circ}\boldsymbol{b}\)\;
\For{\(u\gets 1\) \KwTo \(t\)}{
\(\boldsymbol{a}\leftarrow \boldsymbol{a} - a_{I[u]}\cdot L[u]\)\;
}
\(v\gets 0\)\;
\For{\(u\gets 1\) \KwTo \(n\)}{
\If{\(a_{u}\neq 0\)}{
\(v\gets u\)\;
\Break
}
}
\If{\(v\neq 0\)}{
\(\boldsymbol{\ell}\gets a^{-1}_v\cdot\boldsymbol{a}\)\;
\(L\gets L\cup\{\boldsymbol{\ell}\}\)\;
\(I\gets I\cup\{v\}\)\;
\(t\gets t + 1\)\;
}
}
}
\Return \(L\)
#+end_algorithm

Так как максимальный ранг \(L\) равен \(k=\dim\code{C}\operatorname{\circ}\code{B}\), то алгоритм когда построить систему \(L\) ранга \(k\)
должен будет перебрать ещё \(n_{k+1}\) вектор \(\boldsymbol{c}_i\operatorname{\circ} \boldsymbol{b}_j\) пока не исчерпает все произведения.
На последних итерация ему потребуется выполнить \(2(k+1)n\cdot n_{k+1}\) операций.
Поэтому алгоритм\nbsp{}\ref{alg:hadamard-product-basis} требует не более
\[
N=\sum_{t=1}^{k} (2tn\cdot n_t+n) + 2(k+1)n\cdot n_{k+1}.
\]
операций в поле \(\mathbb{F}_q\).
Заметим, что
\[
\sum_{t=1}^{k+1} n_t = k_1\cdot k_2.
\]
Тогда
\[\begin{aligned}
N&\le \sum_{t=1}^{k} (2(k+1)n\cdot n_t+n) + 2(k+1)n\cdot n_{k+1}\le\\
&\le 2(k+1)\cdot n + 2(k+1)n\sum_{t=1}^{k+1} n_t=2(k+1)n\cdot(k_1k_2+1).
\end{aligned}\]
Так как \(k,k_1,k_2\ge 1\), то \(k+1\le 2k\) и \(k_1 k_2+1\le 2k_1 k_2\), поэтому
окончательно получим, что для построения базиса кода \(\code{C}\operatorname{\circ}\code{B}\) требуется
не более \(8n\cdot k\cdot k_{1}k_{2}\) операций в поле \(\mathbb{F}_q\).
#+end_proof

Следствием из теоремы\nbsp{}\ref{thm:hadamard-product-alg-complexity} является следующая
теорема\nbsp{}\ref{thm:hadamard-product-alg-complexity-2}.

#+caption: Упрощённая оценка сложности построения базиса произведения Адамара
#+name: thm:hadamard-product-alg-complexity-2
#+begin_theorem
Cуществует алгоритм, который по базису \([n]_q\)-кода \(\code{C}\) и базису \([n]_q\)-кода \(\code{B}\)
строит базис кода \(\code{C}\operatorname{\circ}\code{B}\) и имеет сложность не более \(8n^4\)
операций в поле \(\mathbb{F}_q\).
#+end_theorem

#+begin_proof
Оценку теоремы\nbsp{}\ref{thm:hadamard-product-alg-complexity} можно сделать менее точной, но более простой,
если заметить, что \(k,k_1,k_2\le n\).
Тогда число операций в поле \(\mathbb{F}_q\) не будет превосходить величины \(8n^4\).
#+end_proof

При \(q=2\) теоремы\nbsp{}\ref{thm:hadamard-product-alg-complexity} и\nbsp{}\ref{thm:hadamard-product-alg-complexity-2}
дают битовую сложность построения базиса произведения Адамара двух \([n]\)-кодов.

** Связь произведения Адамара линейных кодов с квадратичными формами
** Произведение Адамара кодов Рида--Маллера
#+name: sec:product-of-reed-muller-codes

Установим общий факт о том как выглядит произведение Адамара двоичных кодов Рида--Маллера \(\mathcal{RM}(r,m)\).

#+caption: Произведение Адамара кодов Рида Маллера
#+name: thm:hadamard-prod-of-reed-muller-codes
#+begin_theorem
Справедливо равенство
\[
\mathcal{RM}(r_1,m)\operatorname{\circ} \mathcal{RM}(r_2,m)=\mathcal{RM}(\min(r_1+r_2, m), m).
\]
#+end_theorem

#+begin_proof
Для доказательства будем использовать определение\nbsp{}\ref{def:hadamard-product-whole} произведения Адамара.
Согласно этому определению произведение Адамара кодов \(\mathcal{RM}(r_1,m)\) и \(\mathcal{RM}(r_2,m)\) совпадает с линейной оболочкой множества
#+caption: Множество попарных произведений для Адамара
#+name: eq:hadamard-product-rm-codes
\begin{equation}
\left\{\boldsymbol{f}\operatorname{\circ} \boldsymbol{g}\mid\ \boldsymbol{f}\in \mathcal{RM}(r_1,m),\ \boldsymbol{g}\in\mathcal{RM}(r_2,m)\right\}.
\end{equation}
Степень произведения \(\boldsymbol{f}\operatorname{\circ} \boldsymbol{g}\) не превосходит суммы степеней сомножителей, поэтому
\[
\deg(\boldsymbol{f}\operatorname{\circ} \boldsymbol{g})\le \deg \boldsymbol{f} + \deg \boldsymbol{g} \le r_1+r_2.
\]
При этом степень булевой функции от \(m\) переменных не превосходит \(m\),
поэтому для любых \(\boldsymbol{f}\in\mathcal{RM}(r_1,m)\) и \(\boldsymbol{g}\in\mathcal{RM}(r_2,m)\) выполняется неравенство
\[
\deg(\boldsymbol{f}\operatorname{\circ} \boldsymbol{g})\le \min(r_1+r_2,m).
\]
Значит справедливо включение
\[
\mathcal{RM}(r_1,m)\operatorname{\circ} \mathcal{RM}(r_2,m)\subseteq\mathcal{RM}(\min(r_1+r_2, m), m).
\]
Осталось доказать, что множество\nbsp{}\ref{eq:hadamard-product-rm-codes} содержит базис кода \(\mathcal{RM}(\min(r_1+r_2),m)\).

Согласно утверждению\nbsp{}\ref{prop:min-weight-code-words-generate-rm} в коде \(\mathcal{RM}(\min(r_1+r_2,m),m)\) имеется базис минимального веса.
Поэтому для завершения доказательства теоремы достаточно будет установить, что множество\nbsp{}\ref{eq:hadamard-product-rm-codes}
содержит все векторы минимального веса кода \(\mathcal{RM}(\min(r_1+r_2,m),m)\).

В силу утвеждения\nbsp{}\ref{prop:rm-code-minimal-weight-code-words} все слова минимального веса кода \(\mathcal{RM}(\min(r_1+r_2,m),m)\)
имеют вид
#+caption: Форма слов минимального веса
#+name: eq:thm-min-weight-code-word
\begin{equation}
\boldsymbol{\ell}_1\operatorname{\circ}\boldsymbol{\ell}_2\operatorname{\circ}\ldots\operatorname{\circ}\boldsymbol{\ell}_{\min(r_1+r_2,m)},
\end{equation}
здесь \(\boldsymbol{\ell}_i\in \mathcal{RM}(1,m)\) для всех \(i=1,\ldots,\min(r_1+r_2,m)\).

Разобъём произведение\nbsp{}\ref{eq:thm-min-weight-code-word} на две части:
#+caption: Разбиение слова минимального веса на две части
#+name: eq:thm-min-weight-code-word-2
\begin{equation}
\underbrace{\boldsymbol{\ell}_1\operatorname{\circ}\ldots\operatorname{\circ}\boldsymbol{\ell}_{r_1}}_{r_1}\operatorname{\circ}
\underbrace{\boldsymbol{\ell}_{r_1+1}\operatorname{\circ}\ldots\operatorname{\circ}\boldsymbol{\ell}_{\min(r_1+r_2,m)}}_{\min(r_1+r_2,m)-r_1}.
\end{equation}
Теперь так как \(\min(r_1+r_2,m)\le r_1+r_2\), то \(\min(r_1+r_2,m)-r_1\le r_2\).
Отсюда получаем, что \(\boldsymbol{\ell}_{r_1+1}\operatorname{\circ}\ldots\operatorname{\circ}\boldsymbol{\ell}_{\min(r_1+r_2,m)}\in \mathcal{RM}(r_2,m)\).

А значит из\nbsp{}\ref{eq:thm-min-weight-code-word-2} следует, что любое слово минимального веса\nbsp{}\ref{eq:thm-min-weight-code-word} можно представить в виде такого произведения
Адамара \(\boldsymbol{f}\operatorname{\circ}\boldsymbol{g}\), что \(\boldsymbol{f}=\boldsymbol{\ell}_1\operatorname{\circ}\ldots\operatorname{\circ}\boldsymbol{\ell}_{r_1}\in\mathcal{RM}(r_1,m)\) и
\(\boldsymbol{g}=\boldsymbol{\ell}_{r_1+1}\operatorname{\circ}\ldots\operatorname{\circ}\boldsymbol{\ell}_{\min(r_1+r_2,m)}\in\mathcal{RM}(r_2,m)\).
Поэтому множество\nbsp{}\ref{eq:hadamard-product-rm-codes} содержит все слова минимального веса кода \(\mathcal{RM}(\min(r_1+r_2,m),m)\).
#+end_proof


* Форматирование текста
Можно использовать:
- Жирный шрифт: :: *Это жирный шрифт*
- Курсив: :: /это курсивный шрифт/, но обратите внимание, что при экспорте здесь будет использовать не команда =\textit{}=, а команда =\emph{}=.
- Жирный курсив :: /*это жирный курсив*/ и */этот текст тоже/*.
- Подчеркивание: :: _этот текст подчеркнут_
- Зачеркивание: :: +этот текст зачеркнут+

Но лучше не баловаться подобными украшательствами.
* Формулы
:PROPERTIES:
:CUSTOM_ID: sec:ch1/sec3
:END:

** Ненумерованные одиночные формулы
:PROPERTIES:
:CUSTOM_ID: subsec:ch1/sec3/sub1
:END:
Вот так может выглядеть формула, которую необходимо вставить в строку по тексту: \(x \approx \sin x\) при \(x \to 0\).

А вот так выглядит ненумерованная отдельностоящая формула c подстрочными и надстрочными индексами:
\[(x_1+x_2)^2 = x_1^2 + 2 x_1 x_2 + x_2^2\]

Формула с неопределенным интегралом:
\[\int f(\alpha+x)=\sum\beta\]

При использовании дробей формулы могут получаться очень высокие:
\[\frac{1}{\sqrt{2}+
        \displaystyle\frac{1}{\sqrt{2}+
            \displaystyle\frac{1}{\sqrt{2}+\cdots}}}\]

В формулах можно использовать греческие буквы:
\[\alpha\beta\gamma\delta\epsilon\zeta\eta\theta\vartheta\iota\kappa\varkappa\lambda\mu\nu\xi\pi\varpi\rho\varrho\sigma\varsigma\tau\upsilon\phi\chi\psi\omega\Gamma\Delta\Theta\Lambda\Xi\Pi\Sigma\Upsilon\Phi\Psi\Omega,\]
а также и жирные греческие буквы с помощью команды =\boldsymbol= (см. ссылку https://texfaq.org/FAQ-boldgreek):
\[
\boldsymbol{\alpha\beta\gamma\delta\epsilon\zeta\eta\theta\vartheta\iota\kappa\varkappa\lambda\mu\nu\xi\pi\varpi\rho\varrho\sigma\varsigma\tau\upsilon\phi\chi\psi\omega\Gamma\Delta\Theta\Lambda\Xi\Pi\Sigma\Upsilon\Phi\Psi\Omega}\]

Для добавления формул нужно использовать команды =\(...\)= и =\[...\]=.

** Ненумерованные многострочные формулы

Вот так можно написать две формулы, не нумеруя их, чтобы знаки "равно" были строго друг под другом:
\[\begin{aligned}
    f_W & =  \min \left( 1, \max \left( 0, \frac{W_{soil} / W_{max}}{W_{crit}} \right)  \right), \nonumber \\
    f_T & =  \min \left( 1, \max \left( 0, \frac{T_s / T_{melt}}{T_{crit}} \right)  \right), \nonumber
\end{aligned}\]

Выровнять систему ещё и по переменной \(x\) можно, используя окружение =alignedat= из пакета =amsmath=.
Вот так:
\[|x| = \left\{\begin{alignedat}{2}
     &   & x, \quad & \text{eсли } x\geqslant 0; \\
     & - & x, \quad & \text{eсли } x<0.
\end{alignedat}\right.\]
Здесь первый амперсанд (в исходном LaTeX описании формулы) означает выравнивание по левому краю, второй\nbsp{}--- по \(x\), а третий\nbsp{}--- по слову "если".
Команда =\quad= делает большой горизонтальный пробел.

Ещё вариант:
\[|x|=
    \begin{cases}
        \phantom{-}x, \text{если } x \geqslant 0; \\
        -x, \text{если } x<0.
    \end{cases}\]

Кроме того, для нумерованных формул =alignedat= делает вертикальное
выравнивание номера формулы по центру формулы.
Например, выравнивание компонент вектора:
#+name: eq:2p3
\begin{equation}
    \begin{alignedat}{2}
        {\mathbf{N}}_{o1n}^{(j)} = \,{\sin} \phi\,n\!\left(n+1\right)
        {\sin}\theta\,
        \pi_n\!\left({\cos} \theta\right)
        \frac{
        z_n^{(j)}\!\left( \rho \right)
        }{\rho}\,
         & {\hat{ e}}_{r}\,+      \\
        +\,
        {\sin} \phi\,
        \tau_n\!\left({\cos} \theta\right)
        \frac{
        \left[\rho z_n^{(j)}\!\left( \rho \right)\right]^{\prime}
        }{\rho}\,
         & {\hat{\mathrm e}}_{\theta}\,+ \\
        +\,
        {\cos} \phi\,
        \pi_n\!\left({\cos} \theta\right)
        \frac{
        \left[\rho z_n^{(j)}\!\left( \rho \right)\right]^{\prime}
        }{\rho}\,
         & {\hat{\mathrm e}}_{\phi}\:.
    \end{alignedat}
\end{equation}
Ещё об отступах.
Иногда для лучшей "читаемости" формул полезно немного исправить стандартные интервалы =LaTeX= с учётом логической структуры самой формулы.
Например в формуле\nbsp{}[[eq:2p3]] добавлен небольшой отступ =\,= между основными сомножителями, ниже результат применения всех вариантов отступа:
\[\begin{aligned}
    \backslash!             & \quad f(x) = x^2\! +3x\! +2         \\
    \mbox{по-умолчанию}     & \quad f(x) = x^2+3x+2               \\
    \backslash,             & \quad f(x) = x^2\, +3x\, +2         \\
    \backslash{:}           & \quad f(x) = x^2\: +3x\: +2         \\
    \backslash;             & \quad f(x) = x^2\; +3x\; +2         \\
    \backslash \mbox{space} & \quad f(x) = x^2\ +3x\ +2           \\
    \backslash \mbox{quad}  & \quad f(x) = x^2\quad +3x\quad +2   \\
    \backslash \mbox{qquad} & \quad f(x) = x^2\qquad +3x\qquad +2
\end{aligned}\]

Можно использовать разные математические алфавиты:
\[\begin{aligned}
    \mathcal{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \nonumber  \\
    \mathfrak{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \nonumber \\
    \mathbb{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \nonumber
\end{aligned}\]

Посмотрим на систему уравнений на примере аттрактора Лоренца:
\[\left\{
\begin{array}{rl}
    \dot x = & \sigma (y-x)  \\
    \dot y = & x (r - z) - y \\
    \dot z = & xy - bz
\end{array}\right..\]

А для вёрстки матриц удобно использовать многоточия:
\[\left(\begin{array}{ccc}
a_{11} & \ldots & a_{1n} \\
\vdots & \ddots & \vdots \\
a_{n1} & \ldots & a_{nn} \\
\end{array} \right).\]

В следующем разделе поговорим про нумерованные формулы.

** Нумерованные формулы
:PROPERTIES:
:CUSTOM_ID: subsec:ch1/sec3/sub3
:END:
А вот так пишется нумерованная формула:
#+name: eq:equation1
\begin{equation}
 e = \lim_{n \to \infty} \left( 1+\frac{1}{n} \right)^n.
\end{equation}

Нумерованных формул может быть несколько:
#+name: eq:equation2
\begin{equation}
\lim_{n \to \infty} \sum_{k=1}^n \frac{1}{k^2} = \frac{\pi^2}{6}
\end{equation}

Впоследствии на формулы\nbsp{}[[eq:equation1]] и\nbsp{}[[eq:equation2]] можно ссылаться.

Сделать так, чтобы номер формулы стоял напротив средней строки, можно, используя окружение =multlined= (пакет =mathtools=) вместо =multline= внутри окружения =equation=. Вот так:
#+name: eq:equation3
\begin{equation}
\begin{multlined}
        1+ 2+3+4+5+6+7+\dots + \\
        + 50+51+52+53+54+55+56+57 + \dots + \\
        + 96+97+98+99+100=5050
\end{multlined}
\end{equation}

Уравнения\nbsp{}[[eq:subeq_1]] и\nbsp{}[[eq:subeq_2]] демонстрируют возможности окружения =subequations= (пакет =amsmath=).
#+name: eq:subeq_1
\begin{subequations}
\begin{gather}
        y = x^2 + 1\label{eq:subeq_1-1} \\
        y = 2 x^2 - x + 1\label{eq:subeq_1-2} \\
        y = 3 x^2 - 4x + 8\label{eq:subeq_1-3}
    \end{gather}
\end{subequations}

Ссылки на отдельные уравнения\nbsp{}\ref{eq:subeq_1-1},\nbsp{}\ref{eq:subeq_1-2} и\nbsp{}\ref{eq:subeq_2-1} и вот\nbsp{}\ref{eq:subeq_1-3}.
Нужно использовать команду =\ref=, а не стандартную ссылку ~[[eq:subseq_1-1]]~.
#+name: eq:subeq_2
\begin{subequations}
\begin{align}
        y & = x^3 + x^2 + x + 1\label{eq:subeq_2-1} \\
        y & = x^2
    \end{align}
\end{subequations}

Рассмотрим длинную формулу:
\( a_1+a_2+a_3+a_4+a_5+a_6+a_7+a_8+a_{9}+a_{10}+a_{11}+a_{12}+a_{13}+a_{14}+a_{15}+a_{16}+a_{17}+a_{18}+a_{19}+a_{20}=\sum_{i=1}^{20}a_{i}. \)
Обратите внимание на дублирование знака "+" в этой формуле при переносе на новую строку.
Так принято в русской типографской традиции.
Такого переноса можно достичь с помощью пакет =rmathbr=.

На этом с уравнениями мы закончим.

* Верстка таблиц
** Таблицы и прочее
В разделе мы рассмотрим способ оформления таблиц.
Начнем с самой простой таблицы, которую легко можно сверстать в =org-mode=.
#+caption: Простая таблица
#+name: tab:table1
|-----------------+----------+----------+----------|
| Оконная функция | \( 2N \) | \( 4N \) | \( 8N \) |
|-----------------+----------+----------+----------|
| Прямоугольное   |     8.62 |     8.77 |      8.7 |
|-----------------+----------+----------+----------|
| Ханна           |      7.9 |     7.93 |     7.93 |
|-----------------+----------+----------+----------|
| Хэмминга        |      8.7 |      8.7 |      8.7 |
|-----------------+----------+----------+----------|
| Блэкмана        |     8.73 |      8.7 |     8.77 |
|-----------------+----------+----------+----------|

В таблице\nbsp{}[[tab:table1]] представлены оконные функции.

Та же таблица, но с вертикальными границами.

#+attr_latex: :booktabs t
#+caption: Красивая таблица =booktabs=
#+name: tab:table2
| / | <>                |         <> | <>         |     <>     |
|   | <l>               |        <r> | <l>        |    <c>     |
|---+-------------------+------------+------------+------------|
| # | *Оконная функция* | *\( 2N \)* | *\( 4N \)* | *\( 8N \)* |
|---+-------------------+------------+------------+------------|
| # | Прямоугольное     |       8.62 | 8.77       |    8.7     |
| # | Ханна             |        7.9 | 7.93       |    7.93    |
| # | Хэмминга          |        8.7 | 8.7        |    8.7     |
| # | Блэкмана          |       8.73 | 8.7        |    8.77    |
|---+-------------------+------------+------------+------------|

Смотрите пример в таблице\nbsp{}[[tab:table2]] как форматировать столбцы и каким образом можно создать все границы вокруг строк и столбцов, а также как сделать заглавную ячейка.

Еще один пример таблицы.
#+ATTR_LATEX: :booktabs t :environment longtable :align @{}rr@{}
#+caption: Длинная таблица
#+name: tab:longtable1
|--------------------------------------------+---------------------|
| *Тип*                                      | *Stiffness* in N/mm |
|--------------------------------------------+---------------------|
| Two bearings SKF in radial dir. (supplier) |              167800 |
| Measurement bearings + rotor + device      |                8398 |
| Measurement device                         |               14753 |
| Calculation rotor + bearings               |               19500 |
|--------------------------------------------+---------------------|
| Sim. Rotor + "bearings" (package solid)    |               50900 |
| Sim. Rotor + "joints" (package solid)      |               33320 |
| Sim. Shaft + "bearings" (without package)  |               12000 |
| Sim. Shaft + "bearings" 10 mm              |               20030 |
|--------------------------------------------+---------------------|

* Очень крутая глава
Это очень крутая глава.
** Раздел опять и не очень

Это раздел

*** Это подраздел

Это подраздел.

** Демонстрируем работу со списками

*** Нумерованный список

Рассмотрим список:
1. Первый элемент
2. Второй элемент
   1. Третий элемент
   2. Четвертый элемент
   3. Пятый элемент
      1. Шестой элемент
      2. Седьмой элемент
         1. Восьмой элемент
         2. Девятый элемент
*** Ненумерованный список

Вот пример списка без номеров:
+ Первый элемент
+ Второй элемент
+ Третий элемент
  + Четвертый элемент
  + Пятый элемент
    + Шестой элемент
    + Седьмой элемент
      + Девятый элемент
      + Десятый элемент
Конец списка.
** Математические окружения

Начнем с определения прямоугольного треугольника.

#+name: def:traingle1
#+begin_definition
Треугольник \( ABC \) называется /прямоугольным/, если один из его углов равен \( 90^{\circ}\).
При этом сторона противолежащая углу в \( 90^{\circ} \) называется /гипотенузой/, а стороны прилежащие к этому углу называются /катетами/.
#+end_definition

Докажем несложно утверждение.
#+name: prop:triangle
#+begin_proposition
Сумма квадратов длин катетов \( AB \) и \( AC \) равна квадрату длины гипотенузы \( BC \), т.е. выполняется равенство
\[ AB^{2}+AC^{2} = BC^{2}. \]
#+end_proposition
#+begin_proof
Очень простое доказательство, которое основано, например, на построении квадратов на катетах и гипотенузы, а потом проверки, что площадь квадрата на гипотенузе равна сумме площадей квадратов на катетах.
#+end_proof

Теперь сформулируем теорему.
#+name: thm:triangle
#+begin_theorem
Площадь прямоугольного треугольника равна половине произведения длин катетов.
#+end_theorem

Сделаем важное замечание.

#+name: rem:traingle
#+begin_remark
Особый интерес представляют равнобедренные прямоугольные треугольники.
При этом несложно показать, что равносторонних прямоугольных треугольников не существует.
#+end_remark

#+name: prob:triangle
#+begin_problem
Перечислите все возможные прямоугольные треугольники с натуральной длиной сторон.
Длины таких треугольников формируют, так называемые, пифагоровы тройки.
#+end_problem

Вот ссылки на теорему\nbsp{}[[thm:triangle]] и ссылка на определение\nbsp{}[[def:traingle1]].

** Добавляем немного ссылок

Смотри статью\nbsp{}[cite:@chizhov2023square] там написано про квадрат Адамара линейных кодов.
Кроме того, хорошей статьей является источник\nbsp{}[cite:@mora2023], а книга\nbsp{}[cite:@macwilliams1979] вообще является классикой теории кодирования.

Здесь демонстрируем много ссылок\nbsp{}[cite:@atya1972;@dumer1989;@kim2019;@legeay2012]\nbsp{}--- это ссылки на какие-то источники.
* Заключение :noexport:
:PROPERTIES:
:UNNUMBERED: t
:END:
#+latex: \addcontentsline{toc}{chapter}{Заключение}

# Согласно ГОСТ Р 7.0.11-2011:
# 5.3.3 В заключении диссертации излагают итоги выполненного исследования, рекомендации, перспективы дальнейшей разработки темы.
# 9.2.3 В заключении автореферата диссертации излагают итоги данного исследования, рекомендации и перспективы дальнейшей разработки темы.

Основные результаты работы заключаются в следующем.
1. На основе анализа \ldots
2. Численные исследования показали, что \ldots
3. Математическое моделирование показало \ldots
4. Для выполнения поставленных задач был создан \ldots
И какая-нибудь заключающая фраза.

Последний параграф может включать благодарности.
В заключение автор выражает благодарность и большую признательность научному руководителю Иванову\nbsp{}И.\nbsp{}И. за поддержку, помощь, обсуждение результатов и научное руководство.
Также автор благодарит Сидорова\nbsp{}А.А. и Петрова\nbsp{}Б.Б.
за помощь в работе с образцами, Рабиновича\nbsp{}В.В. за предоставленные образцы и обсуждение результатов, Занудятину\nbsp{}Г.Г. и авторов шаблона
*Russian-Phd-LaTeX-Dissertation-Template* за помощь в оформлении
диссертации.
Автор также благодарит много разных людей и всех, кто сделал настоящую работу автора возможной.
* Список сокращений и условных обозначений :noexport:
:PROPERTIES:
:UNNUMBERED: t
:END:
#+latex: \addcontentsline{toc}{chapter}{Список сокращений и условных обозначений}
# Не является обязательным элементов диссертации

- ППС :: профессорско--преподавательский состав
- ИТКС :: информационно--телекоммуникационная система

* Словарь терминов :noexport:
:PROPERTIES:
:UNNUMBERED: t
:END:
#+latex: \addcontentsline{toc}{chapter}{Словарь терминов}

# Не является обязательным элементом диссертации
- TeX : :: Cистема компьютерной вёрстки, разработанная американским профессором информатики Дональдом Кнутом
- панграмма : :: Короткий текст, использующий все или почти все буквы алфавита

* Список литературы :noexport:ignore:
# #+latex_header_extra: \addbibresource{~/git-projects/mylibrary/library.bib}
#+latex: \printbibliography[heading=bibintoc,title={Список литературы}]

* Списки рисунков :ignore:
\clearpage
\listoffigures
\addcontentsline{toc}{chapter}{Список рисунков}

* Список таблиц :ignore:

# %%% Список таблиц %%%
# % (ГОСТ Р 7.0.11-2011, 5.3.10)
\clearpage
\listoftables
\addcontentsline{toc}{chapter}{Список таблиц}

* Приложения :ignore:
#+latex: \appendix
* Хорошее приложение
Это просто хорошее приложение.

** Подраздел в первом приложении
Подраздел.

** Второй подраздел в первом приложении
И опять подраздел.

*** Подраздел в подразделе первого приложения

Подраздел

* Отличное приложение
Это отличное приложение, которое демонстрирует важность и нужность расчетов.

** Это вторая часть приложения, проверяем как нумеруются подразделы в приложениях

Подраздел.

** Еще подраздел
Еще один подраздел

* Чертежи деталей :noexport:
Здесь можно поместить чертежи деталей.

** Подраздел чертежей

Чертежи

** Подраздел в первом приложении
Подраздел.

** Второй подраздел в первом приложении
И опять подраздел.

*** Подраздел в подразделе первого приложения

Подраздел

* Дополнительная информация :noexport:
Здесь можно поместить чертежи деталей.

** Подраздел чертежей

Чертежи

** Подраздел в первом приложении
Подраздел.

** Второй подраздел в первом приложении
И опять подраздел.

*** Подраздел в подразделе первого приложения

Подраздел

*** И опять подраздел
