#+LATEX_CLASS: extarticle
# #+LATEX_COMPILER: xelatex
#+LATEX_CLASS_OPTIONS: [12pt]
# #+LATEX_HEADER_EXTRA: \usepackage{dejavu}
# #+LATEX_HEADER_EXTRA: \renewcommand{\rmdefault}{cmr}
# #+LATEX_HEADER_EXTRA: \renewcommand{\sfdefault}{cmss}
# #+LATEX_HEADER_EXTRA: \renewcommand{\ttdefault}{DejaVuSansMono-TLF}
# # #+LATEX_HEADER_EXTRA: \usepackage{PTMono}
# #+LATEX_HEADER_EXTRA: \renewcommand{\ttdefault}{PTMono-TLF}
#+LANGUAGE: ru
# #+setupfile: ~/.emacs.d/org-latex-setupfiles/lang/ru.org
# #+setupfile: ~/.emacs.d/org-latex-setupfiles/theorem/plain.org
# #+LATEX_HEADER_EXTRA: \setmainfont[
# #+LATEX_HEADER_EXTRA: ItalicFont     = STIXTwoText-Italic.otf,
# #+LATEX_HEADER_EXTRA:  BoldFont       = STIXTwoText-Bold.otf,
# #+LATEX_HEADER_EXTRA:  BoldItalicFont = STIXTwoText-BoldItalic.otf]{STIXTwoText-Regular.otf}
# #+LATEX_HEADER_EXTRA: \setsansfont{texgyreheros-regular.otf}
# #+LATEX_HEADER_EXTRA: \setmonofont{Inconsolatazi4-Regular.otf}
# #+LATEX_HEADER_EXTRA: \usepackage{unicode-math}
# #+LATEX_HEADER_EXTRA: \setmathfont{STIXTwoMath-Regular.otf}
#+LATEX_HEADER_EXTRA: \usepackage[tocpageword=true, rumath=false]{cmcmsu-gost}
#+LATEX_HEADER_EXTRA: \usepackage[alg, biberon]{cmcmsugost-extra}
#+LATEX_HEADER_EXTRA: \addbibresource{refs.bib}
#+CITE_EXPORT: bibtex
#+title: Произведение Шура--Адамара линейных кодов в анализе теоретико-кодовых криптосистем
#+author: Чижов Иван Владимирович

* Введение
:PROPERTIES:
:UNNUMBERED: t
:END:
#+latex: \addcontentsline{toc}{section}{Введение}

*Актуальность темы*.
Обзор, введение в тему, обозначение места данной работы в мировых исследованиях и т.п., можно использовать ссылки на другие
работы.

Далее приводится пример.

Необходимость проведения научных исследований в целях создания перспективных средств обеспечения информацион ной безопасности определяется Доктриной информационной безопасности Российской Федерации.
Области применения результатов таких исследований определяются Федеральным законом "О безопасности критической информационной инфраструктуры Российской Федерации", постановлением Правительства РФ о реализации государственной программы "Информационное общество", а также рядом приказов отраслевых министерств и ведомств.

В подавляющем большинстве случаев использование средств обеспечения информационной безопасности возможно только после проведения процедуры их сертификации и проверки выполнения требований, предъявляемых ФСТЭК и ФСБ России.
При проведении указанной процедуры важным фактором является получение обоснованных оценок показателей мер защиты, реализуемых средствами защиты информации и, в частности, входящими в их состав криптографическими протоколами.
Высокий уровень защиты информации, обеспечиваемый криптографическими протоколами, является необходимым фактором для обоснования безопасности передаваемой информации.

При передаче информации ее безопасность обеспечивается, как правило, совокупностью нескольких криптографических протоколов:
+ протоколом односторонней, взаимной или многосторонней аутенти фикации участников информационного взаимодействия,
+ протоколом выработки общей для участников взаимодействия ключевой информации, действующей в рамках одной сессии информационного взаимодействия,
+ транспортным протоколом, предназначенным для передачи защищенной информации по каналам связи,
+ процедурами выработки производной ключевой информации, контроля за временем и объемом используемой ключевой информации,
+ вспомогательными протоколами, предназначенными для передачи ошибок информационного взаимодействия, квитирования абонентов, инициализации процедуры выработки нового сессионного ключа и т.п.

Указанной совокупностью протоколов ограничивается область диссертационных исследований.
Выбор конкретного криптографического протокола, применяемого в средстве защиты информации, проводится с учетом большого числа факторов, к которым могут быть отнесены\nbsp{}--- число участников информационного взаимодействия, объем передаваемой информации, срок действия информационной системы или телекоммуникационной сети связи, свойства открытого канала связи, по которому пере дается информация, тип используемой ключевой информации и т.д.

Различные эксплуатационные требования к применяемым криптографическим протоколам приводят к необходимости разработки как универсальных решений и включения таких решений в действующую в Российской Федерации систему стандартизации, так и разработки частных решений, специализированных для конкретных условий эксплуатации.
Однако во всех случаях необходимо обеспечение одинокого высокого уровня защиты информации.

*Степень разработанности темы*.
Этот раздел должен быть отдельным структурным элементом по ГОСТ, но он, как правило, включается в описание актуальности темы.
Нужен он отдельным структурынм элементом или нет --- смотрите другие диссертации вашего совета, скорее всего не нужен.

В диссертации решены актуаль ные и трудные математические задачи, представляющие исключительную важность для обеспечения защищенного взаимодействия средств защиты информации.
В рамках вводных разделов диссертации к каждой главе диссертации представлен исчерпывающий обзор предшествующих результатов по теме исследования, наиболее важные из которых указаны далее в разделе "Краткое содержание работы".

*Целью* данной работы является совершенствование методов построения криптографических протоколов, применяемых для обеспечения защищенного обмена информацией по открытым каналам связи, а также методов получения обоснованных оценок безопасности криптографических протоколов.

Для достижения поставленной цели необходимо было решить следующие *задачи*:
1. уточнить трудоемкость нахождения дискретных логарифмов в группах точек эллиптических кривых и построения параметров эллиптических кривых, обладающих заданной трудоемкостью решения задачи дискретного логарифмирования;
2. разработать способ выработки псевдослучайных последовательностей, удовлетворяющих предъявляемым требованиям по безопасности;
3. построить режим работы блочных шифров, реализующего аутентифицированное шифрование;
4. оценить численные значения показателей эффективности мер защиты для криптографических протоколов, используемых в средствах защиты информации;
5. Исследовать, разработать, вычислить и т.д. и т.п.
6. Исследовать, разработать, вычислить и т.д. и т.п.
7. Исследовать, разработать, вычислить и т.д. и т.п.
8. Исследовать, разработать, вычислить и т.д. и т.п.

*Научная новизна*:
# Опция нужна, чтобы список не отрывался от предыдущей строки
#+attr_latex: options: [beginpenalty=10000]
1. Впервые ...
2. Впервые ...
3. Было выполнено оригинальное исследование ...
4. Впервые получена верхняя оценка числа шагов алгоритма Госпера, используемого для поиска двух совпадающих элементов числовых последовательностей.
   Автором предложен метод дискретного логарифмирования в группе точек эллиптической кривой, в основе которого лежит алгоритм Госпера, и получена асимптотическая оценка трудоемкости предложенного метода.
   Соответствие асимптотической оценки получаемым на практике значениям подтверждено результатами практических экспериментов на ЭВМ.
5. Впервые доказана теорема об иррациональности значений действительных чисел, определяемых рядами специального вида. Предложены новые алгоритмы представления действительных чисел специального вида в виде систематической дроби по произвольному основанию и способ применения предложенных алгоритмов для выработки псевдослучайных последовательностей.
   Получены верхние оценки объема памяти, необходимого для реализации предложенных алгоритмов.

*Теоретическая значимость работы*.
Результаты исследования развивают методы оценки безопасности средств защиты информации, использующих математический аппарат эллиптических кривых.

Автором найден нетривиальный алгоритм решения задачи дискретного логарифмирования в группе точек эллиптической кривой, трудоемкость которого зависит от разыскиваемого неизвестного значения.
Это привело не только к корректировке методов выбора параметров эллиптических кривых, но и к необходимости выработки секретных ключей криптографических схем и протоколов из множества значений, на которых найденный алгоритм имеет максимальную трудоемкость.

Предложенный автором способ выработки псевдослучайных последовательностей удовлетворил требованиям, традиционно накладываемым на криптографические датчики случайных чисел, а также обеспечил ряд дополнительных эксплуатационных характеристик, например, существенно затруднил реализацию датчиков на программируемых логических интегральных схемах.

Разработанный в диссертации новый класс ключевых сжимающих отображений, а также свойства, которыми данный класс обладает, позволили не только разработать несколько новых режимов аутентификационного шифрования для блочных шифров, но и обеспечить возможность высокоэффективной реализации данных режимов на вычислительных средствах с различной архитектурой.

Разработанная в работе методика проведения исследований безопасности криптографических протоколов является на настоящий момент единственным математически обоснованным документом, позволяющим не только проводить комплексные исследования всех факторов, влияющих на безопасность криптографического протокола, но и получать численные значения показателей мер защиты информации.

*Практическая значимость*.
Результаты диссертационных исследований автора были использованы при подготовке положительных заключений о возможности применения ряда государственных стандартов и рекомендаций по стандартизации в области криптографической защиты информации, в частности, ГОСТ Р\nbsp{}34.10-2012 "Процессы формирования и проверки электронной цифровой подписи", Р\nbsp{}1323565.1.004-
2017 "Схемы выработки общего ключа с аутентификацией на основе открытого ключа", Р\nbsp{}1323565.1.018-2018 "Криптографические механизмы аутентификации в контрольных устройствах для автотранспорта", Р 1323565.1.024–2019 "Параметры эллиптических кривых для криптографических алгоритмов и протоколов", Р\nbsp{}1323565.1.028–2019 "Криптографические механизмы защищенного взаимодействия контрольных и измерительных устройств".

*Методология и методы исследования*.
В рамках диссертационного исследования применяются математические методы алгебры, теории чисел, алгебраической геометрии и теории функций комплексного переменного, теории вероятностей и математической статистики, а также теории автоматов.

*Основные положения, выносимые на\nbsp{}защиту*:
#+attr_latex: options: beginpenalty=10000
1. Первое положение
2. Второе положение
3. Третье положение
4. Четвертое положение
5. Доказательство теоремы 1.2 об оценке числа шагов алгоритма Госпера, используемого для поиска двух совпадающих элементов числовых последовательностей.
6. Алгоритм решения задачи дискретного логарифмирования в группе точек эллиптической кривой, основанный на методе Госпера и асимптотическая оценка сложности данного алгоритма.
7. Доказательство теоремы 1.3 об алгоритме дискретного логарифмирования в группе точек эллиптической кривой, использующего информацию о мультипликативном порядке неизвестного, а также точные оценки трудоемкости такого алгоритма и объема используемой им памяти.
8. Доказательство теоремы 2.1 об иррациональности действительных чисел, определяемых рядом \( \alpha=\sum_{k=0}^{\infty}\frac{x_k}{k!} \) для периодической последовательности рациональных чисел \( (x_{k})^{\infty}_{k=0} \).
9. Доказательство утверждений (см. теоремы 2.4 и 2.5) о совпадении разложений в систематическую дробь, а также доказательство критерия (см. теорему 2.6) нормальности действительных чисел из рассматриваемых классов.

*Достоверность* полученных результатов обеспечивается ...
Результаты находятся в соответствии с результатами, полученными другими авторами.

Достоверность полученных результатов обеспечивается строгими математическими выкладками и доказательствами, апробацией на конференциях и семинарах, а также публикациями в рецензируемых научных журналах.
Результаты других авторов, упомянутые в тексте диссертации, отмечены ссылками на соответствующие публикации.

*Апробация работы*.
Основные результаты работы докладывались на: перечисление основных конференций, симпозиумов и т.п.
1. Семинар научного руководителя Московского института электроники и математики им. А.Н. Тихонова федерального государственного автономного образовательного учреждения высшего образования "Национальный исследовательский университет 'Высшая школа экономики'", г.\nbsp{}Москва, 2022 г.
2. Международный симпозиум "Современные тенденции в криптографии CTCrypt", г. Суздаль, 2018, г.\nbsp{}Казань, 2015\nbsp{}г.
3. Семинар "Математические методы криптографического анализа" кафедры информационной безопасности факультета вычислительной математики и кибернетики МГУ им. М.В.Ломоносова, г.\nbsp{}Москва, 2023 г., 2018 г.


*Личный вклад*. Автор принимал активное участие ...

*Публикации*.
Основные результаты по теме диссертации изложены в XX печатных изданиях, X из которых изданы в журналах, индексируемых в Web of Science, Scopus, RSCI и рекомендованных ВАК Минобрнауки России, из них XX\nbsp{}--- в изданиях, индексируемых в Web of Science, Scopus, RSCI.
Также автором получены XX свидетельств о государственной регистрации программ для ЭВМ.

*Объем и структура работы*.
Диссертация состоит из\nbsp{}введения,
четырех глав, заключения, одного приложения, списка литературы.
Полный объём диссертации составляет XXX страниц с\nbsp{}XX\nbsp{}рисунками и\nbsp{}XX\nbsp{}таблицами.
Список литературы содержит XXX\nbsp{}наименований.

* Сведения из теории линейных блоковых кодов
#+name: ch:linear-codes
Теория кодов, исправляющих ошибки, обязана своему появлению классическим работам Клода Шеннона.
В 50-е года XX века в связи с появлением работ Шеннона возник большой поток исследований,
посвящённых построению эффективных схем кодирования информации для передачи по реальным каналам с шумами.
С практической точки зрения существенные ограничения на все схемы кодирования и декодирования дискретных данных накладываются не шенноновской пропускной способностью, а сложностью самого декодера.

Новый подход к решению проблемы был найден в фундаментальных работах Киясу (1957) и Слепяна (1956), Рида и Соломона (1960), Хоквингема (1959), Боуза и Чоудхури (1960), Горенстейна и Цирлера (1961) и Питерсона (1961).
Именно работы этих исследователей фактически положили начало новой области математики\nbsp{}--- теории кодов, исправляющих ошибки.

Коды, исправляющие ошибки, можно рассматривать фактически над любым алфавитом.
Однако наиболее удобным оказывается алфавит, представляющий собой поле Галуа.
В этом случае можно свести задачи кодирования и декодирования к решению алгебраических уравнений.
Развитие компьютерной техники привело к тому, что наиболее часто стали рассматриваться коды над алфавитом\nbsp{}--- полем Галуа характеристики \(2\).

В самом общем случае кодом над некоторым алфавитом называется любое множество слов над этим алфавитом.
Но такое понимание кода является очень широким, а поэтому сложным для исследования.
В силу этого обычно исследуются коды, обладающие некоторым свойством.
Например, таким свойством является линейность.
Линейные коды, т.\nbsp{}е. коды, которые образуют линейное пространство над полем Галуа, на сегодняшний день изучены наиболее полно по сравнению с другими классами кодов.
Именно такие коды находят приложения в современной криптографии.

** Базовые термины и определения
#+name: sec:definitions

Рассмотрим конечное поле \(\mathbb{F}_q\) порядка \(q\).
Тогда векторное пространство размерности \(n\) над полем \(\mathbb{F}_q\) будем обозначать через \(\mathbb{F}^n_q\).
Элементами \( \mathbb{F}^{n}_{q} \), как это принято в теории кодов, исправляющих ошибки, являются векторы-строки \( \vect{v} = \left(v_{1}, v_{2}, \dotsc, v_{n}\right) \).

Через \( \mathbb{F}^{k \times n}_{q} \) обозначим множество всех \( (k \times n) \)-матриц \( \matr{M} \) с элементами из поля \( \mathbb{F}_{q} \).
Так как элементами \( \mathbb{F}^{n}_{q} \) являются векторы строки, поэтому если \( \vect{m}_1, \vect{m}_2, \dotsc ,\vect{m}_{n}\in \mathbb{F}^{k}_{q} \), то запись вида
\[ \matr{M}=\left(\vect{m}^{\top}_{1}, \vect{m}^{\top}_{2}, \dotsc, \vect{m}^{\top}_{n}\right) \]
будет обозначать \( (k \times n) \)-матрицу, столбцом с номером \( j \) которой будет вектор-строка \( \vect{m}_j \), \( 1\le j\le n \).
Соответственно запись вида
\[ \matr{M}= \begin{pmatrix}
             \vect{m}_{1}\\
             \vect{m}_{2}\\
             \vdots\\
             \vect{m}_{n}
             \end{pmatrix} = \left(\vect{m}^{\top}_{1}, \vect{m}^{\top}_{2}, \dotsc, \vect{m}^{\top}_{n}\right)^{\top} \]
означает \( (n \times k) \)-матрицу, строкой с номером \( i \) которой является вектор \( \vect{m}_i \), \( 1\le i\le k \).

Введем естественным способом скалярное произведение векторов пространства \(\mathbb{F}^n_q\).

Пусть \(\vect{x}=(x_1,x_2,\ldots, x_n)\) и \(\vect{y}=(y_1,y_2,\ldots,y_n)\)\nbsp{}--- векторы над полем \(\mathbb{F}_q\).
Тогда скалярным произведением векторов \(\vect{x}\) и \(\vect{y}\) называется элемент \(\left\langle \vect{x}, \vect{y} \right\rangle\in \mathbb{F}_q\)
\[
\left\langle\vect{x}, \vect{y}\right\rangle
\stackrel{\mathrm{def}}{=} x_1\cdot y_1 + x_2\cdot y_2 + \ldots + x_n\cdot y_n.
\]
Здесь «\(+\)» и «\(\cdot\)»\nbsp{}--- соответственно операции сложения и умножения в поле \(\mathbb{F}_q\).
Векторы, скалярное произведение которых равно нулю, принято называть ортогональными.

Введем на пространстве \(\mathbb{F}^n_q\) метрику Хемминга.
Заметим, что обычно в криптографии рассматриваются коды именно в этой метрике.
Хотя в последнее время в различных приложениях появился интерес к линейным кодам в ранговой метрике и в метрике Ли.

Весом Хэмминга \(\operatorname{wt}_H(\vect{x})\) или просто весом \(\operatorname{wt}(\vect{x})\) вектора \(\vect{x}\in \mathbb{F}^n_q\) называется число ненулевых координат этого вектора.

Расстоянием Хэмминга \(\operatorname{d}_H(\vect{x},\vect{y})\) или просто расстоянием \(\operatorname{d}(\vect{x},\vect{y})\) между двумя векторами \(\vect{x}\in \mathbb{F}^n_q\) и \(\vect{y}\in \mathbb{F}^n_q\) называется число координат, в которых эти векторы отличаются, т.е. \(\operatorname{d}_H(\vect{x},\vect{y})=\operatorname{wt}_H(\vect{x}-\vect{y})\).

Для натурального числа \( n \) через \( \str{S}_{n} \) обозначим симметрическую группу, т.\nbsp{}е. группу подстановок \( \elt{\sigma} \) на множестве \( [\![n]\!] \stackrel{\mathrm{def}}{=} \left\{1,2, \dotsc, n\right\} \).

Определим действие группы \( \str{S}_{n} \) на векторы \( \vect{x}\in \mathbb{F}^{n}_{q} \).
Пусть \(\elt{\sigma}\)\nbsp{}--- подстановка из \(\str{S}_{n}\), а \(\vect{x}=(x_1,x_2,\ldots,x_n)\)\nbsp{}--- вектор с элементами из \(\mathbb{F}_q\).
Подстановка \(\elt{\sigma}\) переводит вектор \(\vect{x}\) в вектор \(\vect{x}^{\elt{\sigma}}\), построенный по правилу
\[\vect{x}^{\elt{\sigma}}\stackrel{\mathrm{def}}{=}(x_{\elt{\sigma}^{-1}(1)},x_{\elt{\sigma}^{-1}(2)},\ldots,x_{\elt{\sigma}^{-1}(n)}).\]
Обратим внимание, что координаты вектора \( \vect{x} \) переставляются в соответствии с обратной подстановкой \( \elt{\sigma}^{-1} \), а не \( \elt{\sigma} \).
Такое определение мотивировано тем, что рассматриваются векторы строки, а не векторы столбцы и для согласования действия подстановок с групповой операцией требуется определять это действие описанным способом.

Каждой подстановке \( \elt{\sigma}\in \str{S}_{n}\) можно однозначно сопоставить квадратную \((n\times n)\)-матрицу \(\matr{\sigma}=(s_{ij})_{1\le i,j\le n}\in \mathbb{F}^{n \times n}_{q}\), состоящую только из элементов \( 0 \) и \( 1 \), следующим образом.
Элемент \(s_{ij}=1\), если и только если \(\elt{\sigma}(j)=i\).
Все остальные элементы равны \(0\).
Матрица \(\matr{\sigma}\) называется перестановочной матрицей.

Легко видеть, что действие подстановки \(\elt{\sigma}\) на \(\mathbb{F}^n_q\) можно задать через матричное умножение следующим образом:
\( \vect{x}^{\elt{\sigma}}=\vect{x}\cdot \matr{\sigma}.\)

Действие \( \str{S}_{n} \) на \(\mathbb{F}^n_q\) линейно, т.\nbsp{}е. для любых \(\vect{x}, \vect{y}\in \mathbb{F}^n_q\) и любой подстановки \( \elt{\sigma} \) выполняется равенство \((\vect{x}+\vect{y})^{\elt{\sigma}}=\vect{x}^{\elt{\sigma}}+\vect{y}^{\elt{\sigma}}\).

Пусть \(U\subseteq \mathbb{F}^n_q\).
Тогда \(U^{\elt{\sigma}}\)\nbsp{}--- это множество, состоящее из векторов \(\vect{x}^{\elt{\sigma}}\in \mathbb{F}^n_q\), где \(\vect{x}\in U\).
В силу того, что действие группы \(S_n\) на \(\mathbb{F}^n_q\) линейно, то \(U^{\elt{\sigma}}\)\nbsp{}--- линейное подпространство \(\mathbb{F}^n_q\), если и только если \(U\) является линейным подпространством \(\mathbb{F}^n_q\).

Обозначим через \( \mathbb{F}_{q}[x_1,x_{2}\dotsc, x_{k}] \) кольцо многочленов \( f(x_1, x_2,\dotsc, x_{k}) \) с коэффициентами из поля \( \mathbb{F}_{q} \).
Если \( \vect{x}=(x_1,x_2, \dotsc, x_{k}) \)\nbsp{}--- вектор-столбец формальных переменных, то для краткости вместо \( \mathbb{F}_{q}[x_1,\dotsc, x_{k}] \) будем писать \( \mathbb{F}_{q}[\vect{x};k] \) и вместо \( f(x_1,x_2, \dotsc, x_k) \)\nbsp{}--- \( f(\vect{x}^{\top}) \).

Зафиксируем некоторый кортеж (упорядоченное множество) \( U= \left(\vect{u}_1, \vect{u}_2, \dotsc, \vect{u}_{n}\right) \) векторов из \( \mathbb{F}^k_{q} \), т.е. \( U\subseteq \mathbb{F}^{k}_{q} \) и \( \vect{u}_i=(u_{i,1}, u_{i,2}, \dotsc, u_{i,k})\in \mathbb{F}^{k}_{q} \) для всех \( i=1,2, \dotsc, n \).
Определим линейный оператор \( \operatorname{ev}_{U}: \mathbb{F}_{q}[\vect{x};k] \rightarrow  \mathbb{F}^{n}_{q}\), который каждому многочлену \( f(x_1, x_2, \dotsc, x_{k}) \) ставит в соответствие его вектор значений на элементах \( U \), т.е.
\[ f(x_1,x_2, \dotsc, x_k) \rightarrow \left(f(\vect{u}^{\top}_{1}), f(\vect{u}^{\top}_{2}), \dotsc, f(\vect{u}^{\top}_{n})\right)\in \mathbb{F}^{n}_{q}, \]
где \( f(\vect{u}^{\top}_i) \stackrel{\mathrm{def}}{=} f(u_{i,1}, u_{i,2}, \dotsc, u_{i,k})\in \mathbb{F}^{n}_{q} \)\nbsp{}--- значение полинома \( f \) на векторе \( \vect{u}_{i} \), \( i=1,2, \dotsc, n \).

Пусть \(\matr{G} \in \mathbb{F}_{q}^{k \times n} \) и \( \matr{G} = \left(\vect{g}^{\top}_{1}, \vect{g}^{\top}_{2}, \dotsc, \vect{g}^{\top}_{n}\right) \), где \( \vect{g}_{j}= \left(g_{1,j}, g_{2,j}, \dotsc, g_{k,j}\right) \)\nbsp{}--- столбец с номером \( j \), \( j=1,2, \dotsc, n \), матрицы \( \matr{G} \).
Тогда \( \matr{G} \) можно рассматривать как кортеж ее столбцов и поэтому будет определено отображение \( \operatorname{ev}_{\matr{G}} \), которое многочлену \( f\in \mathbb{F}_{q}[\vect{x};k] \) ставит в соответствие вектор значений \( f \) на столбцах матрицы \( \matr{G} \), т.е.
\[ \operatorname{ev}_{\matr{G}}\!\left(f\right)= \left(f(\vect{g}^{\top}_{1}), f(\vect{g}^{\top}_{2}), \dotsc, f(\vect{g}^{\top}_{n})\right)\in \mathbb{F}^{n}_{q}. \]

Определим теперь действие полной линейной группы \( \str{GL}_{k}(q) \) на кольце \( \mathbb{F}_{q}[\vect{x};k] \).
Если \( \elt{A}\in \str{GL}_{k}(q) \), а через \( \matr{A}\in \mathbb{F}^{k \times k}_{q} \) обозначена невырожденная \( (k \times k) \)-матрица, соответствующая элементу \( \elt{A} \), то каждому многочлену \( f\in \mathbb{F}_{q}[\vect{x};k] \) поставим в соответствие многочлен \( f^{\elt{A}}(\vect{x}^{\top}) \) по правилу
\[ f^{\elt{A}}(\vect{x}^{\top}) \stackrel{\mathrm{def}}{=} f(\matr{A}\cdot\vect{x}^{\top}). \]

Аналогично можно определить действие полной аффинной группы \( \str{GA}_{k}(q) \) на \( \mathbb{F}_{q}[\vect{x};k] \).
Если \( (\elt{A}, \elt{a})\in \str{GA}_{k}(q) \), и пусть \( (\matr{A}\in \mathbb{F}^{k \times k}_{q}, \vect{a}\in \mathbb{F}^{k}_{q}) \)\nbsp{}--- соответствующие элементу \( (\elt{A},\elt{a}) \) невырожденная матрица и вектор, то каждому \( f\in \mathbb{F}_{q}[\vect{x};k] \) сопоставим многочлен \( f^{(\elt{A}, \elt{a})}(\vect{x}^{\top}) \) по правилу
\[ f^{(\elt{A}, \elt{a})}(\vect{x}^{\top}) \stackrel{\mathrm{def}}{=} f(\matr{A}\cdot \vect{x}^{\top}+\vect{a}^{\top}). \]

Обозначим через \( [\![n]\!] \)\nbsp{}--- множество их первых \( n \) натуральных чисел, т.е. \( [\![n]\!] \stackrel{\mathrm{def}}{=} \left\{1,2, \dotsc, n\right\} \).

Если \( T\subseteq [\![n]\!] \) и \( \vect{v}= \left(v_{1}, v_{2}, \dotsc, v_{n}\right)\in \mathbb{F}_{q}^{n} \), то через \( \vect{v}\vert_{T} \) обозначим подвектор вектора \( \vect{v} \), составленный из координат с номерами из множества \( T \), т.е. \( \vect{v}\vert_{T}= \left( v_{i},\ i\in T\right)\in \mathbb{F}_{q}^{n-|T|}\).

Далее определим еще два вектора: \( \vect{v}_{\setminus T} \) и \( \vect{v}_{T} \).
Вектор \( \vect{v}_{\setminus T}\in \mathbb{F}_{q}^{n-|T|} \) имеет длину \( n-|T| \) и состоит из тех координат вектора \( \vect{v} \), номера которых не лежат во множестве \( T \), т.е. \( \vect{v}_{\setminus T}=\vect{v}\vert_{[\![n]\!]\setminus T} \) и он получается из \( \vect{v} \) удалением координат с номерами из множества \( T \).
Вектор \( \vect{v}_{T}\in\mathbb{F}_{q}^{n} \) имеет ту же длину, что \( v \), и получается из \( \vect{v} \) обнулением координат, имеющих номера из множества \( T \).
Получается, что если \( \vect{v}_{T}= \left(u_{1}, u_{2}, \dotsc, u_{n}\right) \), то для всех \( i\in [\![n]\!]\setminus T \) выполняется равенство \( u_{i}=v_{i} \), а для \( i\in T \)\nbsp{}--- равенство \( u_{i}=0\), т.е. \( (\vect{v}_{T})\vert_{T}=\vect{0}^{|T|} \) и \( (\vect{v}_{T})_{\setminus T}=v_{\setminus T} \).

Аналогичную систему обозначений перенесем и на матрицы.

** Линейные коды
#+name: sec:linear-codes-basics

Линейные коды впервые появились в работах Киясу и Слепяна.
В силу того, что эти коды образуют такую хорошо изученную структуру как линейное пространство, они стали основным объектом исследований.
Линейные коды могут быть определены над любым конечным полем.

#+caption: Определение линейного блокового кода длины n
#+name: def:ncode
#+begin_definition
Линейное подпространство \(\code{C}\) пространства \(\mathbb{F}^n_q\) называется \([n]_q\)-кодом.
При этом \(n\) называется длиной кода \(\code{C}\).
Если \(q=2\), то \([n]_2\)-код будем называть просто \([n]\)-кодом.
#+end_definition

#+caption: Определение линейного кода размерности k
#+name: def:nkcode
#+begin_definition
\([n]_q\)-код \(\code{C}\) будем называть \([n,k]_q\)-кодом, если \(\code{C}\) имеет размерность \(k\) как подпространство линейного пространства \(\mathbb{F}^n_q\).
При этом число \(k\) называется размерностью кода \(\code{C}\).
#+end_definition

В силу того, что линейный \([n,k]_q\)-код \(\code{C}\) является линейным конечномерным пространством, то в коде всегда можно выбрать конечный базис векторов этого пространства.
При этом любой вектор из \(\code{C}\) можно представить как линейную комбинацию векторов базиса.
Это замечание подводит к определению порождающей матрицы кода \(\code{C}\).

#+caption: Определение порождающей матрицы кода
#+name: def:generator-matrix
#+begin_definition
Матрица \( \matr{G} \) размера \((k\times n)\) с элементами из \(\mathbb{F}_q\), строками которой являются векторы базиса \([n,k]_q\)-кода \(\code{C}\), называется порождающей матрицей кода \(\code{C}\).
При этом про саму матрицу \(\matr{G}\) будем говорить, что она порождает код \(\code{C}\).
#+end_definition

#+caption: Задание кода через линейные комбинации строк матрицы
#+name: def:generating-matrix
#+begin_definition
Будем говорить, что \((m\times n)\)-матрица \(\matr{G}\) c элементами из \(\mathbb{F}_q\) охватывает код \(\code{C}\), если множество всех возможных линейных комбинаций строк матрицы \(\matr{G}\) совпадает с кодом \(\code{C}\), т.е.
\[ \code{C}=\{\vect{a}\matr{G}\mid\vect{a}\in \mathbb{F}^{m}_{q}\}. \]

Получается, что охватывающая матрица кода в общем случае имеет не полный ранг.
#+end_definition

Если \((k\times n)\)-матрица \(\matr{G}\) охватывает \([n,k]_q\)-код \(\code{C}\), то она является его порождающей матрицей.

Отметим общеизвестный факт.

#+caption: Критерий эквивалентности порождающих матриц
#+name: prop:the-same-generator
#+begin_proposition
Матрицы \(\matr{G}_1\) и \(\matr{G}_2\) размера \((k\times n)\) с элементами из поля \(\mathbb{F}_q\) порождают один и тот же кода \(\code{C}\), если и только если существует такая невырожденная двоичная матрица \(\matr{M}\), что \(\matr{G}_1=\matr{M}\cdot\matr{G}_2\).
#+end_proposition

На основании утверждения\nbsp{}[[prop:the-same-generator]] можно переходить от одной порождающей матрицы кода \(\code{C}\) к другой, просто выполняя линейные операции над строками исходной матрицы.

#+caption: Число порождающих матриц заданного кода
#+name: prop:number-of-generator-matrices
#+begin_proposition
Число порождающих матриц \([n,k]_q\)-кода равно
\[
(q^k-1)(q^k-q)\cdots (q^{k}-q^{k-1}).
\]
#+end_proposition

#+caption: Число различных линейных кодов параметров n k
#+begin_proposition
Число различных \([n,k]_q\)-кодов равно
\[
\frac{(q^n-1)(q^n-q)\cdots (q^n-q^{k-1})}{(q^k-1)(q^k-q)\cdots (q^{k}-q^{k-1})}.
\]
#+end_proposition

#+caption: Информационное окно
#+name: def:inform-set
#+begin_definition
Пусть \( I \subseteq [\![n]\!] \).
Традиционно множество \( I \) называется информационным окном или информационным множеством \( [n,k]_{q} \)-кода \( \mathcal{C} \) с порождающей матрицей \( \matr{G} \), если \( |I|=k \) и подматрица \( \matr{G}\vert_{I} \), составленная из столбцов \( \matr{G} \) с номерами из \( I \), является невырожденной.
#+end_definition

Заметим, что при фиксированном информационном окне \( I \) кода \( \mathcal{C} \) с порождающей матрицей \( \matr{G} \) существует единственная порождающая матрица \( \matr{G}' \) кода \( \mathcal{C} \), у которой в позициях с номерами из \( I \) стоит единичная \( (k \times k) \)- матрица \( \matr{I}_k \), т.е. \( \matr{G}'_{I} = \matr{I}_k \).
Приходим к следующему важному определению.

#+caption: Определение систематической порождающей матрицы
#+name: def:systematic-matrix
#+begin_definition
Матрица \( \matr{G}\in \mathbb{F}^{k \times n}_{q} \) называется систематической, если она имеет вид
\[ \matr{G} = \left(\matr{I}_k\vert \matr{G}'\right), \]
где \( \matr{I}_k \)\nbsp{}--- единичная \( (k \times k) \)-матрица, а \( \matr{G}'\in \mathbb{F}^{(n-k) \times n}_{q} \)\nbsp{}--- произвольная \( ((n-k) \times k) \)-матрица.
#+end_definition

Заметим, что в общем случае у линейного кода может не быть систематической порождающей матрицы, однако у него всегда существует порождающая матрица, которая отличается от систематической только перестановкой столбцов.
Иногда в литературе такую порождающую матрицу из называют полусистематической или почти систематической.

Таким образом, матрица \(\matr{G} = \left(\vect{g}^{\top}_{1}, \vect{g}^{\top}_{2}, \dotsc, \vect{g}^{\top}_{n}\right)\in \mathbb{F}^{k \times n}_{q}\) называется полусистематической, если существуют такие номера столбцов \( 1\le j_1< j_2 < \dotsb < j_{k}\le n \), что
\[
\left(\vect{g}^{\top}_{j_1}, \vect{g}^{\top}_{j_2}, \dotsc, \vect{g}^{\top}_{j_k}\right) = \matr{I}_k,
\]
где \(\matr{I}_{k}\)\nbsp{}--- единичная матрица размера \(k\).
Если \( \matr{G} \) порождает код \( \mathcal{C} \), то в этом случае множество \( I=\left\{j_1,j_2, \dotsc, j_k\right\} \) будет информационным.
Но чтобы не вводить дополнительных сущностей такие матрицы тоже будем называть систематическими, уточняя информационное множество.

Если \([n,k]_q\)-код \(\code{C}\) порождается матрицей \(\matr{G}\), то для любого кодового вектора \(\vect{x}\) кода \(\code{C}\) найдется вектор \(\vect{a}\) длины \(k\) с элементами из \(\mathbb{F}_q\) такой, что
\[
\vect{x}=\vect{a}\cdot \matr{G}.
\]

Значит для линейного кода \(\code{C}\) с порождающей матрицей \(\matr{G}\) можно определить процедуру кодирования (кодер) \(k\)-мерных векторов:
\[
\vect{a}\in \mathbb{F}^{k}_{q} \rightarrow \vect{a}\cdot \matr{G} \in \mathbb{F}^{n}_{q}.
\]

Фактически задание порождающей матрицы \(\matr{G}\) кода \(\code{C}\) определяет свой кодер.

#+caption: Определение систематического кодера
#+begin_definition
Про код \(\code{C}\), порождаемый систематической матрицей (в узком смысле) \(\matr{G}=(\matr{I}_{k}\vert \matr{G}')\) говорят, что он имеет систематический кодер:
\[
\vect{a}=(a_1,\ldots,a_k) \rightarrow \vect{v}=(a_1,\ldots,a_k,\vect{a}\cdot \matr{G}').
\]
Коды, имеющие систематический кодер, называются систематическими.
#+end_definition

#+caption: Определение проверки на чётность кода
#+begin_definition
Проверкой на четность \([n]_q\)-кода \(\code{C}\) называется такой вектор \(\vect{h}\in \mathbb{F}^n_q\), что для всех кодовых векторов \(\vect{c}\in \code{C}\) выполнено равенство
\[
\left\langle\vect{h},\vect{c}\right\rangle =0.
\]
Если вектор \(\vect{h}=(11\ldots 1)\) является проверкой на чётность кода \(\code{C}\), то он называется общей проверкой на четность кода \(\code{C}\).
#+end_definition

#+caption: Связь порождающей матрицы и проверки на чётность
#+begin_proposition
Если код \(\code{C}\) задан своей порождающей матрицей \(\matr{G}\), а \(\vect{h}\)\nbsp{}--- его проверка на четность, то
\[
\matr{G} \cdot \vect{h}^{\top} =\vect{0},\quad \vect{h} \cdot \matr{G}^{\top}=\vect{0}.
\]
#+end_proposition

Множество всех проверок на четность кода \(\code{C}\) является линейным подпространством \( \mathbb{F}^{n}_{q} \).
Приходим к следующему определению.

#+caption: Определение дуального кода
#+begin_definition
Дуальным кодом \(\code{C}^\perp\) к \([n,k]_q\)-коду \(\code{C}\) называется код, который содержит все проверки на четность кода \( \mathcal{C} \).
Код \( \mathcal{C}^{\perp} \) состоит из всех векторов \( \mathbb{F}_{q} \), ортогональных каждому кодовому слову \(\code{C}\), т.\nbsp{}е.
\[
\code{C}^\perp=\left\{\vect{b}\in \mathbb{F}^n_q\;\middle\vert\; (\vect{b},\vect{c})=0\quad \forall\, \vect{c}\in \code{C}\right\}.
\]
#+end_definition

#+caption: Свойства дуального кода
#+name: prop:dual-code-properties
#+begin_proposition
Если \( \mathcal{C} \)\nbsp{}--- \( [n,k]_q \) код, то
1. код \( \mathcal{C}^{\perp} \) является \( [n, n-k]_{q} \)-кодом;
2. верно равенство \( \left(\code{C}^{\perp}\right)^{\perp}=\mathcal{C} \), т.\nbsp{}е. код \( \mathcal{C} \) является дуальным к своему дуальному коду.
#+end_proposition

Из утверждения\nbsp{}[[prop:dual-code-properties]] следует, что если \( \matr{G}^{\perp} \)\nbsp{}--- порождающая матрица кода \( \mathcal{C} \), то каждое кодовое слово \( \vect{c}\in \mathcal{C} \) удовлетворяет соотношению ортогональности \( \matr{G}^{\perp}\cdot \vect{c}^{\top} = \vect{0} \), и при этом, если какой-то вектор \( \vect{x}\in \mathbb{F}^{n}_{q} \) является решением той же системы однородных линейных уравнений, то он будет кодовым словом кода \( \mathcal{C} \).
Тем самым можно говорить, что критерием принадлежности вектора \( \vect{x} \) коду является выполнение равенства \( \matr{G}^{\perp}\cdot \vect{x}^{\top} = \vect{0} \).

#+caption: Определение проверочной матрицы
#+begin_definition
Матрица \(\matr{H}\in \mathbb{F}^{r \times n}_{q}\), для которой выполняется равенство
\[ \matr{H}\cdot \vect{c}^{\top}=\vect{0}, \]
если и только если \( \vect{c}\in \mathcal{C} \) называется проверочной матрицей кода \( \mathcal{C} \).
Другими словами, проверочная матрица охватывает код \( \mathcal{C}^{\perp} \) и имеет ранг \( n-k \).
#+end_definition

Отметим, что в определении проверочной матрицы мы не требуем, чтобы она имела максимальный ранг.
Более того, для некоторых кодов проще построить проверочную матрицу, которая обладает некоторой избыточностью, чем матрицу максимального ранга.

#+caption: Ортогональность порождающей и проверочной матриц
#+begin_proposition
Если \(\matr{G}\) и \(\matr{H}\) соответственно порождающая и проверочная матрица \( [n,k]_{q} \)-кода \(\code{C}\), то выполнены равенства
\[
\matr{H}\matr{G}^{\top}=\vect{0}_{r \times k},\ \ \matr{G}\matr{H}^{\top}=\vect{0}_{k \times r}.
\]
#+end_proposition

Очевидно, что если \(\matr{G}=(\matr{I}_k\vert \matr{G}')\)\nbsp{}--- систематическая порождающая матрица кода \( \mathcal{C} \), то матрица \( \matr{H}=(-\matr{G}'^{\top}\vert \matr{I}_{n-k}) \) будет проверочной матрицей того же кода.

#+caption: Критерий эквивалентности проверочных матриц
#+name: prop:the-same-parity
#+begin_proposition
Матрицы \(\matr{H}_1\in \mathbb{F}^{r \times n}_{q}\) и \(\matr{H}_2\in \mathbb{F}^{r\times k}_{q}\) являются проверочными матрицами одного и того же кода \(\code{C}\), если и только если существует такой \( \elt{A}\in \elt{GL}_r(q) \), что выполняется равенство \(\matr{H}_1=\matr{A}\cdot\matr{H}_2\).
#+end_proposition

Итак, для задания любого линейного кода \( \mathcal{C} \) достаточно указать либо его порождающую матрицу \( \matr{G} \), либо проверочную матрицу \( \matr{H} \).

Иногда код может содержаться в своем дуальном коде, а иногда может с ним совпадать.
Для таких кодов в теории кодирования существуют специальные названия.

#+caption: Определение самодуальных и слабо самодуальных кодов
#+name: def:self-dual
#+begin_definition
Код \(\code{C}\) называется самоортогональным (или слабо самодуальным), если выполняется включение \( \mathcal{C}\subseteq \mathcal{C}^{\perp} \).
Самоортогональный код является самодуальным (или строго самодуальным), если включение становится равенством, т.е. \( \mathcal{C}=\mathcal{C}^{\perp} \).
#+end_definition

Длина и размерность являются фундаментальными параметрами любого кода, характеризующими этот код как линейное пространство.

Введем в рассмотрение третий фундаментальный параметр линейного кода, связанный с метрикой Хемминга и который характеризует способность кода исправлять ошибки.

#+caption: Определение кодового расстояния
#+name: def:code-distance
#+begin_definition
Минимальным расстоянием линейного кода \(\code{C}\) называется число \(d\), равное минимальному расстоянию между различными кодовыми словами кода \(\code{C}\), то есть
\begin{equation*}
d=\min_{\begin{subarray}{l}\vect{c},\vect{b}\in \mathcal{C},\\\vect{c}\neq\vect{b}\end{subarray}}\operatorname{d}(\vect{c},\vect{b}) = \min_{\begin{subarray}{l}\vect{c},\vect{b}\in \mathcal{C},\\\vect{c}\neq\vect{b}\end{subarray}}\operatorname{wt}(\vect{c}-\vect{b}).
\end{equation*}
Кодовое расстояние линейного кода \(\code{C}\) равно минимальному весу ненулевых кодовых слов кода \(\code{C}\):
\begin{equation*}
d=\min_{\vect{c}\in \code{C},\;\vect{c}\neq \vect{0}}\operatorname{wt}(\vect{c}).
\end{equation*}
#+end_definition

В дальнейшем, если \( [n,k]_{q} \)-код имеет кодовое расстояние \(d\), то будем называть такой код \([n,k,d]_{q}\)-кодом.

Кодовое расстояние кода связано с линейно независимыми столбцами проверочной матрицы кода.

#+caption: Критерий минимального расстояния по столбцам проверочной матрицы
#+name: prop:distance-parity-checks
#+begin_proposition
Пусть \(\matr{H}\)\nbsp{}--- проверочная матрица кода \(\code{C}\).
Тогда
1. если код \(\code{C}\) имеет минимальное расстояние \(d\), то в матрице \( \matr{H} \) найдется система из \( d \) линейно зависимых столбцов;
2. если любая система из не более, чем  \(d-1\) столбца матрицы \(\matr{H}\) линейно независимы, но минимальное расстояние кода \( \mathcal{C} \) больше или равно \(d\).
#+end_proposition

Другой важнейшей характеристикой кода \(\code{C}\) является его спектр весов.

#+caption: Определение спектра весов кода
#+name: def:weight-spectrum
#+begin_definition
Спектром весов \([n]_q\)-кода \(\code{C}\) называется вектор
\[
\vect{A}(\code{C})=(A_0,A_1,\ldots,A_{n})\in\mathbb{N}^{n},
\]
у которого координата \(A_i\), \(i=0\ldots n\), равна количеству кодовых слов кода \(\code{C}\) веса Хемминга \(i\), т.е.
\[
A_{i}=\left|\left\{\vect{c}\in\code{C}|\ \operatorname{wt}(\vect{c})=i\right\}\right|,\ \ i=0\ldots n.
\]
#+end_definition

* Форматирование текста
Можно использовать:
- Жирный шрифт: :: *Это жирный шрифт*
- Курсив: :: /это курсивный шрифт/, но обратите внимание, что при экспорте здесь будет использовать не команда =\textit{}=, а команда =\emph{}=.
- Жирный курсив :: /*это жирный курсив*/ и */этот текст тоже/*.
- Подчеркивание: :: _этот текст подчеркнут_
- Зачеркивание: :: +этот текст зачеркнут+

Но лучше не баловаться подобными украшательствами.
* Формулы
:PROPERTIES:
:CUSTOM_ID: sec:ch1/sec3
:END:

** Ненумерованные одиночные формулы
:PROPERTIES:
:CUSTOM_ID: subsec:ch1/sec3/sub1
:END:
Вот так может выглядеть формула, которую необходимо вставить в строку по тексту: \(x \approx \sin x\) при \(x \to 0\).

А вот так выглядит ненумерованная отдельностоящая формула c подстрочными и надстрочными индексами:
\[(x_1+x_2)^2 = x_1^2 + 2 x_1 x_2 + x_2^2\]

Формула с неопределенным интегралом:
\[\int f(\alpha+x)=\sum\beta\]

При использовании дробей формулы могут получаться очень высокие:
\[\frac{1}{\sqrt{2}+
        \displaystyle\frac{1}{\sqrt{2}+
            \displaystyle\frac{1}{\sqrt{2}+\cdots}}}\]

Разные операторы, которые в русском наборе должны выглядеть по-другому:
1. \( \tan\alpha \), ~tan~ (английская традиция), ~tg~ (русская традиция);
2. \( \cot\beta \), ~cot~ (английская традиция), ~ctg~ (русская традиция);
3. \( \csc\gamma \), ~csc~ (английская традиция), ~cosec~ (русская традиция);
4. \( \le \), \(\leqslant\);
5. \( \ge,\ \geqslant \);
6. \( \geq,\ \geqslant \);
7. \( \phi,\ \varphi \);
8. \( \epsilon,\ \varepsilon \);
9. \( \kappa,\ \varkappa \);
10. \( \emptyset,\ \varnothing \)

В формулах можно использовать греческие буквы:
\[\alpha\beta\gamma\delta\epsilon\zeta\eta\theta\vartheta\iota\kappa\varkappa\lambda\mu\nu\xi\pi\varpi\rho\varrho\sigma\varsigma\tau\upsilon\phi\chi\psi\omega\Gamma\Delta\Theta\Lambda\Xi\Pi\Sigma\Upsilon\Phi\Psi\Omega,\]
прямые греческие буквы
\[ \symup{\alpha}\symup{\beta}\symup{\gamma}\symup{\delta}\symup{\epsilon}\symup{\zeta}\symup{\eta}\symup{\theta}\symup{\vartheta}\symup{\iota}\symup{\kappa}\symup{\varkappa}\symup{\lambda}\symup{\mu}\symup{\nu}\symup{\xi}\symup{\pi}\symup{\varpi}\symup{\rho}\symup{\varrho}\symup{\sigma}\symup{\varsigma}\symup{\tau}\symup{\upsilon}\symup{\phi}\symup{\chi}\symup{\psi}\symup{\omega}\symup{\Gamma}\symup{\Delta}\symup{\Theta}\symup{\Lambda}\symup{\Xi}\symup{\Pi}\symup{\Sigma}\symup{\Upsilon}\symup{\Phi}\symup{\Psi}\symup{\Omega} \]
а также и жирные греческие буквы с помощью команды =\symbf= (см. ссылку https://texfaq.org/FAQ-boldgreek):
\[
\symbf{\alpha\beta\gamma\delta\epsilon\zeta\eta\theta\vartheta\iota\kappa\varkappa\lambda\mu\nu\xi\pi\varpi\rho\varrho\sigma\varsigma\tau\upsilon\phi\chi\psi\omega\Gamma\Delta\Theta\Lambda\Xi\Pi\Sigma\Upsilon\Phi\Psi\Omega}\]
также жирные прямые с помощью =\symbfup=
\[ \symbfup{\alpha}\symbfup{\beta}\symbfup{\gamma}\symbfup{\delta}\symbfup{\epsilon}\symbfup{\zeta}\symbfup{\eta}\symbfup{\theta}\symbfup{\vartheta}\symbfup{\iota}\symbfup{\kappa}\symbfup{\varkappa}\symbfup{\lambda}\symbfup{\mu}\symbfup{\nu}\symbfup{\xi}\symbfup{\pi}\symbfup{\varpi}\symbfup{\rho}\symbfup{\varrho}\symbfup{\sigma}\symbfup{\varsigma}\symbfup{\tau}\symbfup{\upsilon}\symbfup{\phi}\symbfup{\chi}\symbfup{\psi}\symbfup{\omega}\symbfup{\Gamma}\symbfup{\Delta}\symbfup{\Theta}\symbfup{\Lambda}\symbfup{\Xi}\symbfup{\Pi}\symbfup{\Sigma}\symbfup{\Upsilon}\symbfup{\Phi}\symbfup{\Psi}\symbfup{\Omega} \]
Для добавления формул нужно использовать команды =\(...\)= и =\[...\]=.

** Ненумерованные многострочные формулы

Вот так можно написать две формулы, не нумеруя их, чтобы знаки "равно" были строго друг под другом:
\[\begin{aligned}
    f_W & =  \min \left( 1, \max \left( 0, \frac{W_{soil} / W_{max}}{W_{crit}} \right)  \right), \nonumber \\
    f_T & =  \min \left( 1, \max \left( 0, \frac{T_s / T_{melt}}{T_{crit}} \right)  \right), \nonumber
\end{aligned}\]

Выровнять систему ещё и по переменной \(x\) можно, используя окружение =alignedat= из пакета =amsmath=.
Вот так:
\[|x| = \left\{\begin{alignedat}{2}
     &   & x, \quad & \text{eсли } x\geqslant 0; \\
     & - & x, \quad & \text{eсли } x<0.
\end{alignedat}\right.\]
Здесь первый амперсанд (в исходном LaTeX описании формулы) означает выравнивание по левому краю, второй\nbsp{}--- по \(x\), а третий\nbsp{}--- по слову "если".
Команда =\quad= делает большой горизонтальный пробел.

Ещё вариант:
\[|x|=
    \begin{cases}
        \phantom{-}x, \text{если } x \geqslant 0; \\
        -x, \text{если } x<0.
    \end{cases}\]

Кроме того, для нумерованных формул =alignedat= делает вертикальное
выравнивание номера формулы по центру формулы.
Например, выравнивание компонент вектора:
#+name: eq:2p3
\begin{equation}
    \begin{alignedat}{2}
        {\mathbf{N}}_{o1n}^{(j)} = \,{\sin} \phi\,n\!\left(n+1\right)
        {\sin}\theta\,
        \pi_n\!\left({\cos} \theta\right)
        \frac{
        z_n^{(j)}\!\left( \rho \right)
        }{\rho}\,
         & {\hat{ e}}_{r}\,+      \\
        +\,
        {\sin} \phi\,
        \tau_n\!\left({\cos} \theta\right)
        \frac{
        \left[\rho z_n^{(j)}\!\left( \rho \right)\right]^{\prime}
        }{\rho}\,
         & {\hat{\mathrm e}}_{\theta}\,+ \\
        +\,
        {\cos} \phi\,
        \pi_n\!\left({\cos} \theta\right)
        \frac{
        \left[\rho z_n^{(j)}\!\left( \rho \right)\right]^{\prime}
        }{\rho}\,
         & {\hat{\mathrm e}}_{\phi}\:.
    \end{alignedat}
\end{equation}
Ещё об отступах.
Иногда для лучшей "читаемости" формул полезно немного исправить стандартные интервалы =LaTeX= с учётом логической структуры самой формулы.
Например в формуле\nbsp{}[[eq:2p3]] добавлен небольшой отступ =\,= между основными сомножителями, ниже результат применения всех вариантов отступа:
\[\begin{aligned}
    \backslash!             & \quad f(x) = x^2\! +3x\! +2         \\
    \mbox{по-умолчанию}     & \quad f(x) = x^2+3x+2               \\
    \backslash,             & \quad f(x) = x^2\, +3x\, +2         \\
    \backslash{:}           & \quad f(x) = x^2\: +3x\: +2         \\
    \backslash;             & \quad f(x) = x^2\; +3x\; +2         \\
    \backslash \mbox{space} & \quad f(x) = x^2\ +3x\ +2           \\
    \backslash \mbox{quad}  & \quad f(x) = x^2\quad +3x\quad +2   \\
    \backslash \mbox{qquad} & \quad f(x) = x^2\qquad +3x\qquad +2
\end{aligned}\]

Можно использовать разные математические алфавиты:
\[\begin{aligned}
    \mathcal{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \nonumber  \\
    \mathfrak{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \nonumber \\
    \mathbb{ABCDEFGHIJKLMNOPQRSTUVWXYZ} \nonumber
\end{aligned}\]

Посмотрим на систему уравнений на примере аттрактора Лоренца:
\[\left\{
\begin{array}{rl}
    \dot x = & \sigma (y-x)  \\
    \dot y = & x (r - z) - y \\
    \dot z = & xy - bz
\end{array}\right..\]

А для вёрстки матриц удобно использовать многоточия:
\[\left(\begin{array}{ccc}
a_{11} & \ldots & a_{1n} \\
\vdots & \ddots & \vdots \\
a_{n1} & \ldots & a_{nn} \\
\end{array} \right).\]

В следующем разделе поговорим про нумерованные формулы.

** Нумерованные формулы
:PROPERTIES:
:CUSTOM_ID: subsec:ch1/sec3/sub3
:END:
А вот так пишется нумерованная формула:
#+name: eq:equation1
\begin{equation}
 e = \lim_{n \to \infty} \left( 1+\frac{1}{n} \right)^n.
\end{equation}

Нумерованных формул может быть несколько:
#+name: eq:equation2
\begin{equation}
\lim_{n \to \infty} \sum_{k=1}^n \frac{1}{k^2} = \frac{\pi^2}{6}
\end{equation}

Впоследствии на формулы\nbsp{}[[eq:equation1]] и\nbsp{}[[eq:equation2]] можно ссылаться.

Сделать так, чтобы номер формулы стоял напротив средней строки, можно, используя окружение =multlined= (пакет =mathtools=) вместо =multline= внутри окружения =equation=. Вот так:
#+name: eq:equation3
\begin{equation}
\begin{multlined}
        1+ 2+3+4+5+6+7+\dots + \\
        + 50+51+52+53+54+55+56+57 + \dots + \\
        + 96+97+98+99+100=5050
\end{multlined}
\end{equation}

Уравнения\nbsp{}[[eq:subeq_1]] и\nbsp{}[[eq:subeq_2]] демонстрируют возможности окружения =subequations= (пакет =amsmath=).
#+name: eq:subeq_1
\begin{subequations}
\begin{gather}
        y = x^2 + 1\label{eq:subeq_1-1} \\
        y = 2 x^2 - x + 1\label{eq:subeq_1-2} \\
        y = 3 x^2 - 4x + 8\label{eq:subeq_1-3}
    \end{gather}
\end{subequations}

Ссылки на отдельные уравнения\nbsp{}\eqref{eq:subeq_1-1},\nbsp{}\eqref{eq:subeq_1-2} и\nbsp{}\eqref{eq:subeq_2-1} и вот\nbsp{}\eqref{eq:subeq_1-3}.
Нужно использовать команду =\eqref=, а не стандартную ссылку ~[[eq:subseq_1-1]]~.
#+name: eq:subeq_2
\begin{subequations}
\begin{align}
        y & = x^3 + x^2 + x + 1\label{eq:subeq_2-1} \\
        y & = x^2
    \end{align}
\end{subequations}

Рассмотрим длинную формулу:
\( a_1+a_2+a_3+a_4+a_5+a_6+a_7+a_8+a_{9}+a_{10}+a_{11}+a_{12}+a_{13}+a_{14}+a_{15}+a_{16}+a_{17}+a_{18}+a_{19}+a_{20}=\sum_{i=1}^{20}a_{i}. \)
Обратите внимание на дублирование знака "+" в этой формуле при переносе на новую строку.
Так принято в русской типографской традиции.
Такого переноса можно достичь с помощью пакет =rmathbr=.

На этом с уравнениями мы закончим.

* Верстка таблиц
** Таблицы и прочее
В разделе мы рассмотрим способ оформления таблиц.
Начнем с самой простой таблицы, которую легко можно сверстать в =org-mode=.
#+caption: Простая таблица
#+name: tab:table1
|-----------------+----------+----------+----------|
| Оконная функция | \( 2N \) | \( 4N \) | \( 8N \) |
|-----------------+----------+----------+----------|
| Прямоугольное   |     8.62 |     8.77 |      8.7 |
|-----------------+----------+----------+----------|
| Ханна           |      7.9 |     7.93 |     7.93 |
|-----------------+----------+----------+----------|
| Хэмминга        |      8.7 |      8.7 |      8.7 |
|-----------------+----------+----------+----------|
| Блэкмана        |     8.73 |      8.7 |     8.77 |
|-----------------+----------+----------+----------|

В таблице\nbsp{}[[tab:table1]] представлены оконные функции.

Та же таблица, но с вертикальными границами.

#+attr_latex: :booktabs t
#+caption: Красивая таблица =booktabs=
#+name: tab:table2
| / | <>                |         <> | <>         |     <>     |
|   | <l>               |        <r> | <l>        |    <c>     |
|---+-------------------+------------+------------+------------|
| # | *Оконная функция* | *\( 2N \)* | *\( 4N \)* | *\( 8N \)* |
|---+-------------------+------------+------------+------------|
| # | Прямоугольное     |       8.62 | 8.77       |    8.7     |
| # | Ханна             |        7.9 | 7.93       |    7.93    |
| # | Хэмминга          |        8.7 | 8.7        |    8.7     |
| # | Блэкмана          |       8.73 | 8.7        |    8.77    |
|---+-------------------+------------+------------+------------|

Смотрите пример в таблице\nbsp{}[[tab:table2]] как форматировать столбцы и каким образом можно создать все границы вокруг строк и столбцов, а также как сделать заглавную ячейка.

Еще один пример таблицы.
#+ATTR_LATEX: :booktabs t :environment longtable :align @{}rr@{}
#+caption: Длинная таблица
#+name: tab:longtable1
|--------------------------------------------+---------------------|
| *Тип*                                      | *Stiffness* in N/mm |
|--------------------------------------------+---------------------|
| Two bearings SKF in radial dir. (supplier) |              167800 |
| Measurement bearings + rotor + device      |                8398 |
| Measurement device                         |               14753 |
| Calculation rotor + bearings               |               19500 |
|--------------------------------------------+---------------------|
| Sim. Rotor + "bearings" (package solid)    |               50900 |
| Sim. Rotor + "joints" (package solid)      |               33320 |
| Sim. Shaft + "bearings" (without package)  |               12000 |
| Sim. Shaft + "bearings" 10 mm              |               20030 |
|--------------------------------------------+---------------------|

* Очень крутая глава
Это очень крутая глава.
** Раздел опять и не очень

Это раздел

*** Это подраздел

Это подраздел.

** Демонстрируем работу со списками

*** Нумерованный список

Рассмотрим список:
1. Первый элемент
2. Второй элемент
   1. Третий элемент
   2. Четвертый элемент
   3. Пятый элемент
      1. Шестой элемент
      2. Седьмой элемент
         1. Восьмой элемент
         2. Девятый элемент
*** Ненумерованный список

Вот пример списка без номеров:
+ Первый элемент
+ Второй элемент
+ Третий элемент
  + Четвертый элемент
  + Пятый элемент
    + Шестой элемент
    + Седьмой элемент
      + Девятый элемент
      + Десятый элемент
Конец списка.
** Математические окружения

Начнем с определения прямоугольного треугольника.

#+name: def:traingle1
#+begin_definition
Треугольник \( ABC \) называется /прямоугольным/, если один из его углов равен \( 90^{\circ}\).
При этом сторона противолежащая углу в \( 90^{\circ} \) называется /гипотенузой/, а стороны прилежащие к этому углу называются /катетами/.
#+end_definition

Докажем несложно утверждение.
#+name: prop:triangle
#+begin_proposition
Сумма квадратов длин катетов \( AB \) и \( AC \) равна квадрату длины гипотенузы \( BC \), т.е. выполняется равенство
\[ AB^{2}+AC^{2} = BC^{2}. \]
#+end_proposition
#+begin_proof
Очень простое доказательство, которое основано, например, на построении квадратов на катетах и гипотенузы, а потом проверки, что площадь квадрата на гипотенузе равна сумме площадей квадратов на катетах.
#+end_proof

Теперь сформулируем теорему.
#+name: thm:triangle
#+begin_theorem
Площадь прямоугольного треугольника равна половине произведения длин катетов.
#+end_theorem

Сделаем важное замечание.

#+name: rem:traingle
#+begin_remark
Особый интерес представляют равнобедренные прямоугольные треугольники.
При этом несложно показать, что равносторонних прямоугольных треугольников не существует.
#+end_remark

#+name: prob:triangle
#+begin_problem
Перечислите все возможные прямоугольные треугольники с натуральной длиной сторон.
Длины таких треугольников формируют, так называемые, пифагоровы тройки.
#+end_problem

Вот ссылки на теорему\nbsp{}[[thm:triangle]] и ссылка на определение\nbsp{}[[def:traingle1]].

** Добавляем немного ссылок

Смотри статью\nbsp{}[cite:@chizhov2023square] там написано про квадрат Адамара линейных кодов.
Кроме того, хорошей статьей является источник\nbsp{}[cite:@mora2023], а книга\nbsp{}[cite:@macwilliams1979] вообще является классикой теории кодирования.

Здесь демонстрируем много ссылок\nbsp{}[cite:@atya1972;@dumer1989;@kim2019;@legeay2012]\nbsp{}--- это ссылки на какие-то источники.
* Работа с листингами и псевдокодом в разных пакетах
Ниже идут четыре теста: код Python с русскими комментариями, код C с русскими
комментариями, псевдокод через ~listings~, псевдокод через =algorithm2e=.

** Python в listings с русскими комментариями

\begin{lstlisting}[language=Python, caption={Тест Python-кода с русскими комментариями}]
def gcd(a, b):
    # Находим наибольший общий делитель
    while b != 0:
        # Меняем местами значения
        a, b = b, a % b
    return a

n = 84
m = 30
print("НОД =", gcd(n, m))  # Ожидается 6
\end{lstlisting}

** C в listings с русскими комментариями

\begin{lstlisting}[language=C,caption={Тест C-кода с русскими комментариями}]
#include <stdio.h>

/* Простая функция суммы */
int sum_upto(int n) {
    int s = 0;
    // Суммируем числа от 1 до n
    for (int i = 1; i <= n; ++i) {
        s += i;
    }
    return s;
}

int main(void) {
    printf("%d\n", sum_upto(10)); // Должно вывести 55
    return 0;
}
\end{lstlisting}

** Псевдокод средствами listings

\begin{lstlisting}[style=pseudocode,caption={Псевдокод через listings}]
procedure BinarySearch(A, x)
begin
    // A -- отсортированный массив
    left  := 0
    right := length(A) - 1

    while left <= right do
    begin
        mid := floor((left + right) / 2)

        if A[mid] = x then
            return mid
        else
            if A[mid] < x then
                left := mid + 1
            else
                right := mid - 1
    end

    return -1
end
\end{lstlisting}

** Псевдокод средствами algorithm2e

\begin{algorithm}[h]
\caption{Бинарный поиск}
\KwInput{Отсортированный массив $A[0 \dots n-1]$, значение $x$}
\KwOutput{Индекс элемента или $-1$}

left $\gets 0$\;
right $\gets n - 1$\;

\While{left $\le$ right}{
    mid $\gets$ $\lfloor$(left + right)/2$\rfloor$\;
    \Comment{Проверяем средний элемент}

    \uIf{$A$[mid] = $x$}{
        \KwRet mid\;
    }
    \uElseIf{$A$[mid] < $x$}{
        left $\gets$ mid + 1\;
    }
    \Else{
        right $\gets$ mid - 1\;
    }
}

\KwRet $-1$\;
\end{algorithm}

** Ещё один тест algorithm2e с русскими комментариями

\begin{algorithm}[h]
\caption{Алгоритм Евклида}
\KwInput{Целые числа $a,b$}
\KwOutput{$\gcd(a,b)$}

\While{$b \ne 0$}{
    $r \gets a \bmod b$\; \Comment{Остаток от деления}
    $a \gets b$\;
    $b \gets r$\;
}
\KwRet $a$\;
\end{algorithm}

* Тестируем оформление и работу с библиографией

Теория информации была впервые строго сформулирована в работе
[cite:@Shannon1948].

Классический учебник по системе TeX можно найти в книге [cite:@Knuth1984].

Основы теории алгоритмов изложены в русском учебнике [cite:@aho1979].

Для знакомства с теорией кодирования полезна монография [cite:@macwilliams1979].

Эти источники часто используются в математике и информатике.


* Заключение
:PROPERTIES:
:UNNUMBERED: t
:END:
#+latex: \addcontentsline{toc}{section}{Заключение}

# Согласно ГОСТ Р 7.0.11-2011:
# 5.3.3 В заключении диссертации излагают итоги выполненного исследования, рекомендации, перспективы дальнейшей разработки темы.
# 9.2.3 В заключении автореферата диссертации излагают итоги данного исследования, рекомендации и перспективы дальнейшей разработки темы.

Основные результаты работы заключаются в следующем.
1. На основе анализа \ldots
2. Численные исследования показали, что \ldots
3. Математическое моделирование показало \ldots
4. Для выполнения поставленных задач был создан \ldots
И какая-нибудь заключающая фраза.

Последний параграф может включать благодарности.
В заключение автор выражает благодарность и большую признательность научному руководителю Иванову\nbsp{}И.\nbsp{}И. за поддержку, помощь, обсуждение результатов и научное руководство.
Также автор благодарит Сидорова\nbsp{}А.А. и Петрова\nbsp{}Б.Б.
за помощь в работе с образцами, Рабиновича\nbsp{}В.В. за предоставленные образцы и обсуждение результатов, Занудятину\nbsp{}Г.Г. и авторов шаблона за помощь в оформлении
диссертации.
Автор также благодарит много разных людей и всех, кто сделал настоящую работу автора возможной.
* Список таблиц :ignore:

# %%% Список таблиц %%%
# % (ГОСТ Р 7.0.11-2011, 5.3.10)
\clearpage
\listoftables
\addcontentsline{toc}{section}{Список таблиц}

* Список литературы (biblatex) :ignore:

#+LATEX: \printbibliography[heading=bibintoc]

* Приложения :ignore:
#+latex: \appendix
* Хорошее приложение
Это просто хорошее приложение.

** Подраздел в первом приложении
Подраздел.

** Второй подраздел в первом приложении
И опять подраздел.

*** Подраздел в подразделе первого приложения

Подраздел

* Отличное приложение
Это отличное приложение, которое демонстрирует важность и нужность расчетов.

** Это вторая часть приложения, проверяем как нумеруются подразделы в приложениях

Подраздел.

** Еще подраздел
Еще один подраздел
